### PR TITLE
Chromium integration

### PR DESCRIPTION
**Pull request by jaragunde**
Add meta-browser submodule and add meta-browser and meta-gnome layers to bblayers.conf. These all are required to build Chromium.

These changes need to be combined with this PR for meta-genivi-dev: https://github.com/GENIVI/meta-genivi-dev/pull/53

We don't add `chromium-wayland` to the default GDP image yet, as we have only been able to test it on one of the supported platforms. The package needs to be added to `IMAGE_INSTALL_append` in local.conf.

### CODE REVIEW

**Comment by chbae** [comment]
@jaragunde 
Which device do you test? qemux86, rpi2 or 3, minnowboard?
I'll test on this week on rpi3.

**Comment by jaragunde** [comment]
hi @chbae, I've been working mainly with a minnowboard. I tried to generate a rpi3 build and it didn't work, another person has stumbled upon the same problem first and hopefully will provide a fix: http://lists.openembedded.org/pipermail/openembedded-devel/2017-February/110973.html

**Comment by zeenix** [comment]
@jaragunde So shall I close this PR until you have it working on RPI3 as well? RPI, minnowboard and Qemu would be the targets I'd want it to work on at least, before your work in merged.

Also, I've heard the sound is still not functional? I don't think we should block the PR for that at all but would be nice to get that fixed before GDP 12.

**Comment by zeenix** [comment]
@jaragunde I mean if RPI would take more than a few days, we could close this for now, otherwise let's keep it open.

**Comment by jaragunde** [comment]
@zeenix I wouldn't close the PR yet; in the current state, it won't break anything because the compilation of chromium is still optional (requires `IMAGE_INSTALL_append = " chromium-wayland").

Let me update the PR to use Chromium 53 instead of 48; my rebase patches were recently merged into meta-browser. Video playback is much smoother in this revision, one of the issues you had detected.

Regarding the sound, I found the root of the problem and a workaround; Pulseaudio is set to use the null sink as the default one, so Chromium takes it. This can be fixed with `pacmd "set-default-sink AlsaPrimary"` and made permanent in `/etc/pulse/default.pa`. Ideally, the browser should talk to the GENIVI Audio Manager but I think this workaround is good enough now. A future task would be to build a proper GENIVI browser based on Chromium, which would integrate with the Audio Manager, Persistence, etc.

**Comment by zeenix** [comment]
@jaragunde Ah ok, understood. About proper Chromium integration, do you think it'd be a good GSoC project or you think you guys will be doing that before summer already? If you think it's a good idea to have it as a GSoC project, please add it to the ideas wiki: https://at.projects.genivi.org/wiki/display/GDP/GDP+GSoC+ideas

**Comment by jaragunde** [comment]
The browser work, I find it a bit tough for a GSoC; we will try to start it soon.

I said I was going to push a new version of the PR to build Chromium 53; I've realized there is one required patch waiting to be merged into meta-browser. I will ping maintainers about it and will update this PR as soon as it's merged.

Is there anything pending on https://github.com/GENIVI/meta-genivi-dev/pull/53? We could move that one forward in the meantime.

**Comment by zeenix** [comment]
> Is there anything pending on my side for GENIVI/meta-genivi-dev#53? We could move that one forward in the meantime.

I don't think so. Shortlog of first commit could be better but it's not bad. :)

**Comment by jaragunde** [comment]
Updated PR with the latest meta-browser master, now we have all the commits we need from that project.

**Comment by jaragunde** [comment]
I completely messed this PR up by pushing the wrong branch. I'm not allowed to reopen, and cannot push the correct branch because it's closed.

**Comment by jaragunde** [comment]
New PR created: https://github.com/GENIVI/genivi-dev-platform/pull/59

**Pull request closed without merging**
