### PR TITLE
 meta-iot-web: Add new layer for iotivity-node support #58 (reopen)

### PR DESCRIPTION
**Pull request by rzr**
This is following instructions given at:
https://github.com/GENIVI/genivi-dev-platform/pull/58

One merged please merge:
https://github.com/GENIVI/meta-genivi-dev/pull/63

### CODE REVIEW

**Comment by rzr** [comment]
There are a few example in the package, check also:
https://wiki.iotivity.org/automotive#work_in_progress

**Comment by rzr** [comment]
Any idea what's wrong with porter board ? I need a login to view the log.

cc: @zeenix @ns950

**Comment by gunnarx** [comment]
@rzr Don't worry - Porter is currently failing also on master branch so it should have nothing to do with your PR.

**Comment by slawr** [comment]
@rzr Hi Phil I had a look at the log for the PR. It is failing for the same reason that master is failing - no one providing libgudev since a change in the GDP image packages. I'll be fixing that once I've pushed a GDP PR I'm preparing. It's at do_rootfs() time so very late in the build process. I'm not a GDP maintainer and of course there is a small chance that adding your layer might go onto through its own do_rootfs() task error, but that seems remote. So like Gunnar I would expect this PR is ok.

**Comment by rzr** [comment]
Ok thank @slawr for keeping us informed about the state of master branch.

@zeenix is there a bug to track about this ?

To help, I can double check fixes if any.

**Comment by zeenix** [comment]
@rzr yes: https://at.projects.genivi.org/jira/browse/GDP-561

**Comment by slawr** [comment]
I've started to look at GDP-561. Updating there.

**Comment by gunnarx** [comment]
Adding my +1 which I missed before.  Were you waiting for me?  I don't see anything blocking this.   We're all convinced GDP-561 is causing the check failure.  All other checks are OK.  Or what is holding it up now?

**Comment by zeenix** [comment]
I hadn't merged yet cause I was hoping @chbae will provide feedback from his testing since he asked for how to test this all. But yeah, this is just adding the layer so let's merge this at least first.

**Pull request merged**
