### PR TITLE
pull meta-genivi-ocf-demo

### PR DESCRIPTION
**Pull request by rzr**
this is the 3rd step of integration 

previous one was :  https://github.com/GENIVI/meta-genivi-ocf-demo/pull/2

https://at.projects.genivi.org/jira/projects/GOCF/issues/GOCF-27

### CODE REVIEW

**Comment by chbae** [comment]
@jonathanmaw, @tom--pollard @toscalix 
We need to discuss about this kind of commits. Please wait for merging this.

**Comment by tom--pollard** [comment]
Sure @chbae

**Comment by rzr** [comment]
No problem take your time to decide meawhile I will document how to build and use genivi-ocf-demo-image

**Comment by as2902b** [comment]
@chbae, @rzr, can we have an IRC chat about this issue in #automotive ?

**Comment by rzr** [comment]
Sure we can discuss , when ? I might be busy this week , but you can try to reach me , I am adding  @gunnarx @jeremiah  in loop too

**Comment by tom--pollard** [comment]
For yesterdays GDP call comments, the general consensus seemed to be that new components that bring added functionality to GDP should be built by default (at least to start with). This would me adding the ocf/oic demo packages to our default package lists

**Comment by rzr** [comment]
So what does it mean in term of integration ? 
Of course once this layer is merged we can also include packages in main genivi demo image.

Please confirm the plan, It made sense to have all ocf related packages into a layer and make it available to any yocto based distros.

**Comment by iamsanjeev** [comment]
tom--pollard, rzr
Sorry for the delayed response. 
I might be paraphrasing what @gunnarx suggested in 
https://github.com/GENIVI/genivi-dev-platform/pull/3

The contents in meta-genivi-ocf-demo are examples of the iotivity usage.
They don't add value to the GDP by themselves.
In future, we plan to add more samples to this layer to illustrate different ways to use meta-oic.
(for ex, client/server mode, secure/insecure mode, multi language examples etc)

Also, if I remember correct, meta-oic ships with a set of default examples which is already part of GDP.
(@rzr, please confirm)

**Comment by rzr** [comment]
So instead, I will make an other PR to add iotivity tests apps in default image and check it's fine.

And we can keep the demos aside (on documentation), I had in mind to have everything related to this effort to land into this layer, I was working on adding iotivity-node to be run on GDP, but it might not be relevant.

**Comment by toscalix** [comment]
On the "Demo days", there was little point in including code into GDP if there were no functionality to show. In the new context, the "Development days" we assume that new functionality does not come in a bulk but little by little. We assume that this involve some risk.  But in general we are receptive to initiatives like this one, where there is an expectation of bringing innovation/functionality into GDP in the near future.

**Comment by tom--pollard** [comment]
@rzr I totally agree with you if you wish to keep the ocf related packages in a separate layer (for instance meta-rvi has rvi-core), I simply think that we don't need to define a separate genivi-dev-platform image recipe with those appended, when they could just be built by default in GDP

**Comment by rzr** [comment]
Ok then I have a idea that can fit your strategy and which is more generic.
Will keep ou updated

**Comment by philrob17** [comment]
All, IMHO the work on genivi-ocf is for the time being a prototype implementation, meaning that we do not know about the final software architecture for the interface between OCF and the connected vehicle. The objective is to have a generic interface (with no transformation of interface / resource description) suitable for OCF, W3C, OMA and GENIVI connected platform. This will take some time. In addition,  the genivi-ocf gateway is not integrated in GDP yet, this will occur over the next weeks. Hence my recommendation is to keep genivi-ocf-demo as a separate layer until design and interface description get stabilitized.

**Comment by gunnarx** [comment]
Hey guys.  Sorry for being late into this.  I think Philippe summed it up well however.

And Sanjeev, thanks for referencing my previous comment.

Also, toscalix describes it correctly that the platform must now provide good support for development, not only completely finished functions.  However, I still think it is good if we can see a balance.  At least some demonstration application should probably be there if we are going to includes something as default, and an evaluation of how many of our "users" will likely start developing on top of a certain feature.

Also, it is important that the demo thing is something people can easily run - if it requires custom hardware and such then we will have something similar to the current AA branch, it is there but is not so widely usable and risk that it gets limited testing.

One good thing about Github is that someone like RzR could maintain a fork of the project for a while and develop it into something that really feels ready to merge.

OK, so those are general principles.  For this particular case I must admit I have not fully understood what we will "get" if we merge the PR.   But Philippe writes: "... the genivi-ocf gateway is not integrated in GDP yet, this will occur over the next weeks"
In that case it seems to me it is perfect to keep this integration on a fork for a while, and maybe then return to the merging into GDP official?

**Comment by rzr** [comment]
For months I was looking for a pattern that could help cross distro maintainance (demo images and more) and I come to this proposal :

    - meta-ocf-automotive/
       - recipes/apps/iotivity-example.bb
       - recipes/image/ocf-automotive-demo-image.bb :
         require recipes-image/images/core-image-minimal.bb
         IMAGE_INSTALL += " iotivity-example "
       - meta-genivi-dev/
         - meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bbappend :
           require recipes/image/ocf-autotmotive-demo-image.bb
       - meta-agl-demo/
         - meta-agl-demo/recipe-platform/images/agl-demoplatform-ocf.bb :
           require agl-demo-image.bb
           require ocf-auto-demo-image.bb
         - meta-agl-demo/recipe-platform/core/iotivity_git.bb
       - meta-tizen_common/
         - meta-tizen_common/recipes/images/tizen_common-core-image.bbappend :
           require ocf-autotmotive-demo-image.bb
       - ...

Then the base layer meta-ocf-automotive and meta-ocf-automotive/meta-$distro layer should me added to BBLAYERS in local.conf


Of course, If this cooperation model is good it can be replicated with other projects or tech.

Comments are welcome.

ps: I will check that on master branch of GENIVI once @tom--pollard merge it.

**Comment by tom--pollard** [comment]
@rzr I think your plan is entirely reasonable, and will help you maintain the layer for cross platform compatibility. Using 'sub layers' in this way is very useful.

**Comment by chbae** [comment]
```
- meta-genivi-dev/
     - meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bbappend :
       require recipes/image/ocf-autotmotive-demo-image.bb
```
Actually i'm not prefer to adding image recipe in genivi-dev-platform.bb.
My recommendation options is: 
- Create packagegroup in meta-genivi-ocf-demo

**Comment by rzr** [comment]
that  meta-ocf-automotive/meta-genivi-dev sublayer 
will be part of meta-ocf-automotive , 

It wont touch gdp expect for pulling layer as this change  , but could append a packagegroup as you're suggesting.

**Comment by chbae** [comment]
@rzr 
1. The same meta layer name is not good approach even though meta-genivi-dev is under meta-ocf-automitive. Could you add some prefix like meta-genivi-dev-ocf?

2. I'm not prefer to add genivi-dev-platform.bbappend in meta-ocf-automotive/meta-genivi-dev because genivi-dev-platform.bb should be managed in only meta-genivi-dev. If you would like to add iotivity-example in genivi-dev-platform, it's good to add it as packagegroup as I suggested.

Thanks.

**Comment by rzr** [comment]
What's is the problem with keeping the same name , that way it's more generic and could be scripted ?

I got the idea from this file : 
https://gerrit.automotivelinux.org/gerrit/#/c/5663/2/meta-agl-bsp/conf/layer.conf

So what is done with BSP here could be done the same way for distros.

Ok I will check for package groups as It would be good a have a common strategy between distros, everyone agrea on that ?

**Comment by chbae** [comment]
@rzr 
Thanks for your comments.

> hat's is the problem with keeping the same name , that way it's more generic and could be scripted ?
> 
> I got the idea from this file : 
> https://gerrit.automotivelinux.org/gerrit/#/c/5663/2/meta-agl-bsp/conf/layer.conf

@rstreif 
Could you give me your comments? Now I'm confused to use same meta layer name.

**Comment by rzr** [comment]
what about just integrating iotivity upstream sample apps to demo images ? @iamsanjeev  @philrob17 @gunnarx

**Comment by karthikeyanprakash** [comment]
I am looking for IoTivity Demo files into the official image. Is there any process going on for that?

**Comment by rzr** [comment]
@karthikeyanprakash "I am looking for IoTivity Demo files into the official image. Is there any process going on for that?"
 
OK I still believe it can be helpful to have iotivity in demo images but @jonathanmaw closed this PR without really explaining why, so It stalled in this shape and I put all my efforts into upstream project to make integration easier for any yocto based distros ...

So if you want to test latest (supported) release

1/ First try to build GDP

2/ Then you need to ugprade meta-oic to 1.1.1+ which has my change in: 

http://git.yoctoproject.org/cgit/cgit.cgi/meta-oic/commit/?id=1f8e30c592c1c352a0e5cba1926391a2f9eb4d26

3/  Finally just add iotivity package group to desired image (which one?)

IMAGE_INSTALL += " packagegroup-iotivity "

Ask me for help and keep an eye on this page for related resources:

https://wiki.iotivity.org/yocto

**Comment by slawr** [comment]
Hi @rzr @karthikeyanprakash the last replies from the likes of Gunnar talked about taking another look at this once it had matured on a fork. If that is now the case I would suggest discussing it with the maintainers again.

I do not know if you are aware but GDP is under going a change in maintainers. The work done by the engineers at Codethink is migrating to engineers at Pelagicore. You may need to give them a week or two to get up to speed.

**Comment by rzr** [comment]
Sure, meanwhile I have just rebuilt iotivity 1.1.1 for current master on pi2 : 

https://github.com/GENIVI/genivi-dev-platform/pull/52

more to come once merged

**Comment by rzr** [comment]
https://github.com/GENIVI/genivi-dev-platform/pull/52
is now merged

may we consider to build iotivity in gdp with this:
https://github.com/GENIVI/meta-genivi-dev/pull/47

Once everything checked , I will update meta-oic to be aligned to 1.2-rel expected to supported by some  devices

**Pull request closed without merging**
