### PR TITLE
gdp-new-hmi.bb: Log using DLT and ivi-logging

### PR DESCRIPTION
**Pull request by frznlogic**

### CODE REVIEW

**Comment by chbae** [comment]
I can't find ivi-logging recipe. Where is it?

**Comment by gunnarx** [comment]
@chbae It's not there and that's why the PR is failing.  Oscar sent the PR to meta-ivi but maybe we should start by having it in meta-genivi-dev first.  See here: https://github.com/GENIVI/meta-ivi/pull/43

**Comment by chbae** [comment]
@gunnarx Thanks. I'll review GENIVI/meta-ivi#43.

**Comment by frznlogic** [comment]
This is relying on the https://github.com/GENIVI/genivi-dev-platform/pull/104 to be pulled in first

**Comment by gunnarx** [comment]
Yes. @chbae, please review #104 if you can, because some updates were made to the recipe.

**Comment by gunnarx** [comment]
Looks good to me.  After merging #104, we could rebase this and confirm a succesful build check.

**Pull request merged**
