### PR TITLE
thud... (WIP)

### PR DESCRIPTION
**Pull request by gunnarx**
This is just a start.  Update meta-ivi and also update meta-ivi dependent layers (poky, oe, gplv2)
however there are probably more layers that should update.

Also some BSPs don't support it yet, so it will be a work in progress.

### CODE REVIEW

**Comment by mirzak** [comment]
Pushed some updates here: https://github.com/mirzak/genivi-dev-platform/commits/outgoing/thud

Two fixes are required in upstream repositories, here is a local git diff:

```
mirza.krak@mirzak:~/genivi/genivi-dev-platform/meta-sdl$ git diff
diff --git a/conf/layer.conf b/conf/layer.conf
index ec329d1..9717135 100644
--- a/conf/layer.conf
+++ b/conf/layer.conf
@@ -8,4 +8,4 @@ BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
 BBFILE_COLLECTIONS += "sdl"
 BBFILE_PATTERN_sdl = "^${LAYERDIR}/"
 BBFILE_PRIORITY_sdl = "6"
-LAYERSERIES_COMPAT_sdl = "sumo"
+LAYERSERIES_COMPAT_sdl = "sumo thud"
mirza.krak@mirzak:~/genivi/genivi-dev-platform/meta-sdl$ cd ..
mirza.krak@mirzak:~/genivi/genivi-dev-platform$ cd meta-qt5/
mirza.krak@mirzak:~/genivi/genivi-dev-platform/meta-qt5$ git diff
diff --git a/conf/layer.conf b/conf/layer.conf
index b2a4fbc..ee177ab 100644
--- a/conf/layer.conf
+++ b/conf/layer.conf
@@ -30,3 +30,5 @@ IMAGE_FEATURES[validitems] += "qtcreator-debug"
 QT_GIT ?= "git://github.com/qt"
 QT_LABS_GIT ?= "git://github.com/qt-labs"
 QT_GIT_PROTOCOL ?= "git"
+
+LAYERSERIES_COMPAT_qt5-layer = "thud"
```

Up until now LAYERSERIES_COMPAT sanity checks have been warnings, but as of `thud` this is an parse error. We can not bbappend it so changes are needed in upstream.

meta-sdl is probably manageable, but meta-qt5 is a bit tricky since it is based on a very old managablebranch/commit we might need to fork it?

**Comment by mirzak** [comment]
Actually there is no change required for meta-qt5. As it does not set LAYERSERIES_COMPAT at all, it is still a warning saying "you should set LAYERSERIES_COMPAT". 

But in meta-sdl case, it has explicitly stated that it is only compatible with `sumo` and hence this will need an update.

**Comment by slawr** [comment]
I sent [PR #9](https://github.com/gunnarx/genivi-dev-platform/pull/9) to @gunnarx working branch to update the R-Car support for thud using YBSP v3.15.0. Please merge.

**Comment by gunnarx** [comment]
This will not be updated.

**Pull request closed without merging**
