### PR TITLE
Rocko combined

### PR DESCRIPTION
**Pull request by gunnarx**
Yet another PR... 
* combines #175 and [chbae/#2](https://github.com/chbae/genivi-dev-platform/pull/2)
* Fixes sign-off on the meta-intel commit (thanks @slawr)

Sure it's a bit messy right now with all the redundant PRs, but it's an effective way to get some test builds on these different combinations, so it should be all good in the end.

If this one goes well, the next step is to add back Chromium again, taken from #174, which should then work on R-Car (but as we can see there seem to be a few issues on other platforms)

### CODE REVIEW

**Comment by slawr** [comment]
@gunnarx thanks for the merge.

Just a reminder, for R-Car Gen 3 YBSP v3.6.0 you want the gfx/mmp package [R-Car Gen3 Evaluation Software Package for Linux
for Yocto v3.6.0 and Wayland 1.13 /Weston 2.0](https://www.renesas.com/en-us/solutions/automotive/rcar-demoboard-2.html) on the CI.

Which consists of the userland and kernelland downloads (R-Car_Gen3_Series_Evaluation_Software_Package_for_Linux-20180326.zip and R-Car_Gen3_Series_Evaluation_Software_Package_of_Linux_Drivers-20180326.zip) 

Without the update I expect the build will still succeed but if you want to actually use it you will likely hit problems.

**Comment by gunnarx** [comment]
Update: added a CI script fix dad30c5f0598f46b38d2c67ea7eb0aa4d993ef59 fixing a bug that might be responsible for the R-Car failed build in CI

**Comment by gunnarx** [comment]
> Just a reminder, for R-Car Gen 3 YBSP v3.6.0 you want the gfx/mmp package R-Car Gen3 Evaluation Software Package for Linux for Yocto v3.6.0 and Wayland 1.13 /Weston 2.0 on the CI.

For completeness - note that the CI agents that support Renesas builds now have this version of the drivers (but unfortunately not the old ones, which means GDP 13 can no longer be built in CI for Renesas. Soon that should not be a concern any more)

This PR could probably be closed in favor of #177, but I think we need to debug the final issues and merge and then we can clean up redundant PRs.

**Comment by slawr** [comment]
> For completeness - note that the CI agents that support Renesas builds now have this version of the drivers (but unfortunately not the old ones, which means GDP 13 can no longer be built in CI for Renesas. Soon that should not be a concern any more)

Just a suggestion but should the need arise I would use the SGX directory var to handle this. To handle GDP 13 simply point the SGX directory var of the CI script at the directory for the v2.23.1 gfx packages as a pre-requisite for the pipeline.

**Comment by gunnarx** [comment]
Added on one commit: Mirza's SDK fix that removes qtwebkit also from SDK (already removed from image).

**Comment by gunnarx** [comment]
The new Chromium seems to work OK, so close this in favor of #177

**Pull request closed without merging**
