### PR TITLE
meta-linaro: Bump meta-linaro fixing magicwand dep

### PR DESCRIPTION
**Pull request by frznlogic**
74dacb3 image-magic 6.9.2: resurrect old version to match python-wand
75ff66e python-wand: add SRCREV, fix QA issue and add comment about imagemagick version
034d680 meta-optee: python-wand: upgrade to latest release 0.4.4
a16e349 linaro-image-minimal-initramfs: the uboot class was merged into core-image

Signed-off-by: Oscar Andreasson <oscar.andreasson@pelagicore.com>

### CODE REVIEW

**Comment by slawr** [comment]
Hi, when doing an YBSP v2.23 update I typically take the opportunity to update/test associated layers as well. I noticed the imagemagick changes in meta-linaro and wondered if they would fix the issue Gunnar reported. However when I looked at the others changes between the current sha and HEAD there was some change I wasn't sure about. I would need to revisit the diffs to remind myself what the specific concern was, but at the time I decided to bump that till later.

If all is good, fine, but I'm raising a flag that the changes need accessing.

**Comment by frznlogic** [comment]
@slawr I'm guessing you mean these two commits?

> 034d680 meta-optee: python-wand: upgrade to latest release 0.4.4
> a16e349 linaro-image-minimal-initramfs: the uboot class was merged into core-image
> 

I'm rebuilding the images from scratch and I'll test them if they work etc. Is there anything in special you'd like me to keep an eye out for?

**Comment by gunnarx** [comment]
Sorry, hacking a bit on the pipeline configs.  The non-Renesas builds were therefore stopped and therefore report failure, but they should not be affected by this PR (and that was tested before the rebase also).

**Comment by gunnarx** [comment]
Build check on R-Car OK.  Awaiting tested binary.

**Comment by gunnarx** [comment]
Reminder (for myself) - upon merge, remove ImageMagick from package list on build hosts since the recipe is fixed (and... the builds ought to be sandboxed now anyway)

**Comment by slawr** [comment]
> @slawr I'm guessing you mean these two commits?
> 
>>     034d680 meta-optee: python-wand: upgrade to latest release 0.4.4

> >     a16e349 linaro-image-minimal-initramfs: the uboot class was merged into core-image
> 
> I'm rebuilding the images from scratch and I'll test them if they work etc. Is there anything in special you'd like me to keep an eye out for?

Sorry @frznlogic I missed your question. I think the initramfs commit is fine as it applies only to a linaro distro image. I think it was more the python changes although looking at them again I wonder what my specific concern was. It may have just been a concern around the delays caused by the impact of any issue.

Gunnar and I discussed in a BIT call. He was happy to treat this as a separate update to my YBSP update PR and I was happy for this to be tested to see if there was any impact and to merge if there wasn't.

**Comment by gunnarx** [comment]
Rebased on latest master and pushed back for another build check for R-Car.  

I'll make a judgement call and skip build checks for the other targets since they should not be affected.  
(If they were forcibly stopped they will be noted as failed, just ignore that)

**Comment by gunnarx** [comment]
ImageMagick was removed from the [package list](https://github.com/genivigo/gocd-setup/blob/master/common_build_dependencies) that controls the build agents

**Pull request merged**
