### PR TITLE
Uitest

### PR DESCRIPTION
**Pull request by bertcay**

### CODE REVIEW

**Comment by zeenix** [comment]
@bertcay a mistake?

**Comment by bertcay** [comment]
Yes a mistake ... Sorry ...
To be finalized before being opensourced :)

Sorry again


On Mar 1, 2017 12:50 PM, "Zeeshan Ali" <notifications@github.com> wrote:

@bertcay <https://github.com/bertcay> a mistake?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GENIVI/genivi-dev-platform/pull/63#issuecomment-283320496>,
or mute the thread

**Comment by bertcay** [comment]
I removed it immediatly

**Comment by zeenix** [comment]
@bertcay no worries. :)

**Pull request closed without merging**
