### PR TITLE
Step meta-genivi-dev to include dragonboard SDK fix:

### PR DESCRIPTION
**Pull request by gunnarx**
The meta-genivi-dev PR built successfully for all targets that have been set up:
http://go.genivi.org/go/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/36/build/1
http://go.genivi.org/go/pipelines/GDP-Yocto-PORTER-meta-genivi-dev-GITHUB-PR/30/build/1
http://go.genivi.org/go/pipelines/GDP-Yocto-RPI2-meta-genivi-dev-GITHUB-PR/48/build/1
http://go.genivi.org/go/pipelines/GDP-Yocto-MINNOWBOARD-meta-genivi-dev-GITHUB-PR/34/build/1

Now that meta-genivi-dev merged the PR let's try moving that into g-d-p.git also.

### CODE REVIEW

**Comment by gunnarx** [comment]
Github PR builds are running again.

**Comment by gunnarx** [comment]
Hmm strange new error on Minnowboard: Package nss failing?  I triggered another try on the same to see what happens.

**Comment by gunnarx** [comment]
Minnoboard was rebuilt on another agent and the error went away.  It was:

12:37:42.603 | unix_rand.c:1090:6: error: 'readdir_r' is deprecated [-Werror=deprecated-declarations]

I can only imagine compiler version as differing between go agents.

But as far as I can understand, it is glibc that has deprecated this function, in a quite recent version:   glibc 2.24, released 2016-08-05.

...and glibc shouldn't reasonably differ between two builds, even on different build agents, since it is built from recipes by Yocto.   It should not matter what the host operating system of the build agent uses.

**Comment by gunnarx** [comment]
@tom--pollard @chbae feel free to review and consider.  
The build checks are now successful with the above concern in mind.

@chbae, do you know if nss-native was a new build dependency introduced with this change, or is it an old one that we just have not noticed?

**Comment by tom--pollard** [comment]
Builds ok for me, on my minnowboard target. (Side note, it's nice to see that github shows submodule diffs if also hosted on github now :) )

**Comment by chbae** [comment]
@gunnarx nss-native is not new component. It already had it in old build.

**Pull request merged**
