### PR TITLE
Update meta renesas and local.conf

### PR DESCRIPTION
**Pull request by slawr**
Update to the current upstream Renesas R-Car Gen 2 meta-renesas. Also simplify the Porter and Silk board local.conf thanks to changes introduced in meta-renesas. See commit messages for details.

Confirmed to work with the Porter board with the following build config (the GDP SHA before G11):
Build Configuration:
BB_VERSION        = "1.28.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "porter"
DISTRO            = "poky-ivi-systemd"
DISTRO_VERSION    = "10.0.1"
TUNE_FEATURES     = "arm armv7a vfp neon callconvention-hard cortexa15"
TARGET_FPU        = "vfp-neon"
meta              
meta-yocto        
meta-yocto-bsp    = "HEAD:fc45deac89ef63ca1c44e763c38ced7dfd72cbe1"
meta-ivi          
meta-ivi-bsp      = "HEAD:43ac797bda5dd72ad89771fc95e25296fc8b8b61"
meta-oe           
meta-filesystems  
meta-ruby         = "HEAD:ad6133a2e95f4b83b6b3ea413598e2cd5fb3fd90"
meta-qt5          = "HEAD:ea37a0bc987aa9484937ad68f762b4657c198617"
meta-genivi-dev   = "HEAD:88aaaea7318ba1c4c4dda494af847c868b392760"
meta-rust         = "HEAD:f13ac9d48ae928b761d7be204fa8f877d41e7099"
meta-oic          = "HEAD:69146eaf8bc05c74c377e731b7e16d82854a4659"
meta-erlang       = "HEAD:4d7eacc8e6593934ed5b0c8abc3d3e9dc339d849"
meta-rvi          = "HEAD:de9d548fe35e2cee8688faaae910b4f6f7fea17e"
meta-renesas      
meta-rcar-gen2    = "genivi-10-bsp-1.10.0:98e3453096c4c38fc4819be6888c83d43903383d"
meta-multimedia   = "HEAD:ad6133a2e95f4b83b6b3ea413598e2cd5fb3fd90"

### CODE REVIEW

**Comment by tom--pollard** [comment]
Hi @slawr thanks for making this public!

Now how to handle this.....

**Comment by slawr** [comment]
Don't worry M2 Kolesch and Gen 3 are coming next... :)

**Comment by chbae** [comment]
I'm sorry that GDP doesn't support GDP10 as you known.

**Comment by slawr** [comment]
@chbae That is certainly planned now the GDP Maintainers have decided to move to it.

In the meantime re your vote down the PR was sent because I discussed whether I should send it in a recent GDP meeting (last week?) and I was asked to by the maintainers... So a little frustrating when I spent time preparing and testing it if it is now not wanted, but based on the direction stated in today's call I'll support it in a G10 fork in my github.

**Comment by chbae** [comment]
@slawr 
I'm very sorry. It's better to support this PR in your github.

@tom--pollard, @RobertAJMarshall, @toscalix 
Please give us your opinion.

**Comment by gunnarx** [comment]
@slawr Is this now replaced by #44 or do we need both?

**Comment by slawr** [comment]
@gunnarx that confused me for a moment as the email I received linked to #44 - seemed to be asking if #44 was still required :)

Anyway the first commit no. The second commit (880d1db505d5df985a86ec9973c1456213205724) is still relevant. Although not strictly required for a working system it simplifies the local.conf following an update I made in meta-renesas. I can add it to #44 if it makes it easier <he assumes github allows such things>?

**Comment by slawr** [comment]
This PR has been open long enough that the meta-renesas update is now superseded by one in PR #44. The local.conf commit has been added to PR #44 and I am now closing this PR

**Pull request closed without merging**
