### PR TITLE
Upgrade qt to v5.6.0

### PR DESCRIPTION
**Pull request by chbae**
meta-genivi-dev
0923a59 README.md: Update meta-qt5 branch information
6ae5dba systemd: Add QT_QPA_PLATFORM environment
4e7e1a3 Rebase ivi shell patches for v5.6.0 in qtwayland
00474a0 packagegroup-gdp-qt5: Remove unnecessary components
d09c752 Remove unnecessary bbclass and add remove-libtool.bbclass
        from oe-core

meta-qt5
Use krogoth branch

[GDP-280] Upgrade Qt to v5.6

Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

### CODE REVIEW

**Comment by chbae** [comment]
This PR should be merged with https://github.com/GENIVI/meta-genivi-dev/pull/22

**Comment by chbae** [comment]
@tom--pollard, @RobertAJMarshall 
I tested on my raspberrypi3. Please review this PR.

Thanks

**Comment by RobertAJMarshall** [comment]
Builds for qemux86-64

**Comment by tom--pollard** [comment]
Also builds for me. I've created a PR for Baseline11 support https://github.com/GENIVI/meta-genivi-dev/pull/23 which also includes the commits for qt5.6 (krogoth) support. If we merge this PR first I will rebase and amend

**Comment by chbae** [comment]
@tom--pollard, @RobertAJMarshall 
Please +1 or -1 after your testing. I'll merge this change.

Thanks.

**Pull request merged**
