### PR TITLE
meta-renesas: rebase on yocto bsp v2.23.1

### PR DESCRIPTION
**Pull request by slawr**
Early push of update to meta-renesas to allow people to try it before merging.
Tested to build and and run ok on M3 Starter Kit.
Further testing on-going.

Task tracked in JIRA as [GDP-767]

----
The current community Genivi Yocto BSP Pyro support in meta-renesas is
based on upstream (Krogoth) Yocto BSP v2.19. Since then the upstream has
moved to v2.23 and the Genivi Yocto BSP has been rebased on it.
Therefore update to this newer Genivi Yocto BSP.

The corresponding gfx/mmp packages for this release are "R-Car Gen3
Evaluation Software Package for Linux for Yocto v2.23.0 and Wayland 1.13
/ Weston 2.0"

52a5df3 rcar-gen3: packagegroup: Create new packagegroups for GFX packages
f8e9978 rcar-gen3: libegl: Create new recipe to fix build dependency issues
bc0a99e rcar-gen3: Add .gitignore
f3b8689 rcar-gen3: Use flexible coding style for Renesas datadir
006e8f7 rcar-gen3: Correct coding style of IMAGE_FSTYPES
b2db674 rcar-gen3: cms-user-module: Update MD5SUM and lib version for new CMS pkgs
c303665 rcar-gen3: copyscript: Update MD5SUM for ADSP packages
0ad1ac3 rcar-gen3: copyscript: Update MD5SUM for Audio packages
6951325 rcar-gen3: copyscript: Update MD5SUM for Video packages
6e003ca rcar-gen3: EthernetAVB: Update SRCREV to follow the latest version
70db163 rcar-gen3: libalacdla-l: Update SRCREV to follow the latest version
5c74ca1 rcar-gen3: libflacdla-l: Update SRCREV to follow the latest version
1396b78 rcar-gen3: gstreamer: Update SRCREV to follow the latest version
e325704 rcar-gen3: gstreamer: Clean gstreamer recipes to facilitate maintenance
705d8f7 rcar-gen3: kernel-module-vsp2driver: Update SRCREV to follow the latest version
5c8216d rcar-gen3: kernel-module-vspm: Update SRCREV to follow latest version
21c8a03 rcar-gen3: MMNGR: Update SRCREV for driver to follow latest version
f40f31d rcar-gen3: libgbm: Update SRCREV to follow the latest version
b733169 rcar-gen3: wayland-kms: Update SRCREV to follow the latest version
b69c97f rcar-gen3: weston: Update recipe and SRCREV to follow the latest version
03fb4dd rcar-gen3: mesa: Rename mesa bbappend
23a3ef7 rcar-gen3: mesa: Remove installation of eglmesaext.h
cf3bea7 rcar-gen3: gles-user-module: Remove patch to include header from mesa
4c59b6d rcar-gen3: copyscript: Update MD5SUM for ICCOM packages
c909fac rcar-gen3: IPL: Update SRCREV to follow the latest version
4c5fb52 rcar-gen3: u-boot: Upgrade version according to Linux BSP to v3.5.6
9da249f rcar-gen3: linux-renesas: linux-renesas: Upgrade Linux BSP from v3.5.5 to v3.5.8
85b7865 rcar-gen3: ULCB: Add default SOC_FAMILY for ULCB
2cd35b4 rcar-gen3: gstreamer1.0-omx: Fix issue downloading from HTTP/HTTPS proxy
7405103 rcar-gen3: EthernetAVB: Update SRCREV to follow latest version
b941502 rcar-gen3: copyscript: Update MD5SUM for ADSP packages
979c108 rcar-gen3: kernel-module-vsp2driver: Update SRCREV to follow latest version
d3032b0 rcar-gen3: VSPM: Update SRCREV for VSPM and VSPM I/F driver
99b7da7 rcar-gen3: kernel-module-mmngr: Update version and correct compile option
eeb2358 rcar-gen3: copyscript: Update MD5SUM for ICCOM packages
6ad142d rcar-gen3: arm-trusted-firmware: Update SRCREV to follow latest version
8d26f47 rcar-gen3: u-boot: Update u-boot to v3.5.4
f704621 rcar-gen3: linux-renesas: Update BSP to v3.5.5

[GDP-767] Update meta-renesas to rebase on YBSP v2.23

Signed-off-by: Stephen Lawrence <stephen.lawrence@renesas.com>

### CODE REVIEW

**Comment by gunnarx** [comment]
All build checks OK but thosechecks don't publish the binaries for testing.  I set up a build to do that:
https://go.genivi.org/go/tab/build/detail/GDP-Yocto-R-Car-YBSP-223/1/build/1/init_and_bitbake

**Comment by slawr** [comment]
Thanks. It seems the new M3 Starter Kit pipeline build [failed](https://go.genivi.org/go/tab/build/detail/GDP-Yocto-R-Car-YBSP-223/1/build/1/init_and_bitbake#). Llooking at the console output it looks like bitbake completed ok, but there was a failure in the post-build provisioning steps.

I've updated the JIRA to report that H3 Starter Kit builds ok.

**Comment by frznlogic** [comment]
@slawr are you ok with pulling this PR in, or do you want to continue working on it?

**Comment by slawr** [comment]
Hi @frznlogic, I would have said merge it. However there has actually been a point release upstream to [v2.23.1](https://github.com/renesas-rcar/meta-renesas/releases/tag/Renesas-Yocto-v2.23.1) that has some useful fixes in it. It should be a straight forward merge. The gfx and mmp packages are the same as for v2.23 for instance. It is more a BSP update.

So I was thinking it should just be 1-2 days for me to rebase on v2.23.1, sanity test on the Starter Kits and then update the PR, i.e. made sense to wait for that. People could pull this PR if they urgently need v2.23 for some reason. So unless planning on your side meant that it would not actually be merged till several days later I would wait. If there would be such a delay I would merge now and treat v2.23.1 as a second step. Happy to do either. Let me know.

**Comment by frznlogic** [comment]
I'm fine with waiting a little bit for it ;). I'd like to have it done by the end of next week, do you think it's possible?

**Comment by slawr** [comment]
Should be. With a following wind I would hope to have updated the PR by Tuesday.

**Comment by slawr** [comment]
I'm getting a strange build issue after the v2.23.1 rebase.

opkg-native do_install task fails:
```
| make  install-data-hook
| make[3]: Entering directory `/data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/build'
| chmod +x /data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/image/data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/recipe-sysroot-native/usr/share/opkg/intercept/*
| make[3]: Leaving directory `/data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/build'
| make[2]: Leaving directory `/data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/build'
| make[1]: Leaving directory `/data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/build'
| sed: can't read /data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/image/data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/recipe-sysroot-native/lib/systemd/system/opkg-configure.service: No such file or directory
| WARNING: exit code 2 from a shell command.
| ERROR: Function failed: do_install (log file is located at /data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/tmp/work/x86_64-linux/opkg-native/1_0.3.4-r0/temp/log.do_install.20958)
ERROR: Task (virtual:native:/data/steve/genivi-13/h3sk/genivi-dev-platform/gdp-src-build/../poky/meta/recipes-devtools/opkg/opkg_0.3.4.bb:do_install) failed with exit code '1'

It happened on both the M3 SK and H3 SK builds so is easily reproducible. Both builds were built from in my existing local build trees rather than from scratch.

Curious as v2.23.1 makes no changes to recipes-devtools.
If you are interested I pushed the working branch [pyro_upstream-v2.23.1](https://github.com/slawr/meta-renesas/tree/stevel/pyro_upstream-v2.23.1) to my github, otherwise no change to this PR.

**Comment by slawr** [comment]
Hmm from this IRC [log ](https://www.yoctoproject.org/irc/%23yocto.2017-03-22.log.html)it may be an sstate issue.

**Comment by slawr** [comment]
Fixed the issues and pushed them to my github working branch @ [pyro_upstream-v2.23.1](https://github.com/slawr/meta-renesas/tree/stevel/pyro_upstream-v2.23.1).

Building both official boards overnight. If there are still problems in the morning then I will move to merge the PR as it is with YBSP v2.23.0 support and update v2.23.1 later.

**Comment by slawr** [comment]
OK. Updated meta-renesas built ok and passed sanity testing on M3 Starter Kit so pushed an update to the PR for merging. I have kept seperate commits for the (original) move to meta-renesas based on upstream v2.23.0 and the move forward to v2.23.1. Reasoning is that they were two separate releases.

I now propose these for merging once CI tests are complete.

**Comment by slawr** [comment]
I see the M3 Starter Kit CI build failed with the following fetch error:
```
16:01:21.107 ERROR: python-pyqt-5.3.1-r1 do_fetch: Fetcher failure for URL: 'http://downloads.sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.3.1/PyQt-gpl-5.3.1.tar.gz'. Unable to fetch URL from any source.
16:01:21.107 ERROR: python-pyqt-5.3.1-r1 do_fetch: Function failed: base_do_fetch
16:01:21.107 ERROR: Logfile of failure stored in: /var/lib/go-agent/pipelines/GDP-Yocto-r-car-m3-starter-kit-GITHUB-PR/gdp-src-build/tmp/work/aarch64-poky-linux/python-pyqt/5.3.1-r1/temp/log.do_fetch.26067
16:01:21.108 NOTE: recipe python-pyqt-5.3.1-r1: task do_fetch: Failed
16:01:21.114 ERROR: Task (/var/lib/go-agent/pipelines/GDP-Yocto-r-car-m3-starter-kit-GITHUB-PR/gdp-src-build/../meta-genivi-dev/meta-genivi-dev/recipes-devtools/python/python-pyqt_5.3.1.bb:do_fetch) failed with exit code '1'
```

Strange one as I can fetch that tar ball fine with wget locally.

**Comment by slawr** [comment]
My local build succeeds because my download cache contains a PyQt-gpl-5.3.1.tar.gz download that matches the meta-genivi-dev/meta-genivi-dev/recipes-devtools/python/python-pyqt_5.3.1.bb checksums. It would seem unusual but I guess the upstream tar ball may have been updated. I wonder though why the other builds succeeded then? meta-renesas has no bbappend for that recipe.

**Comment by slawr** [comment]
Rebased on gdp master branch to pull in Gunnar's update for python-pyqt recipe.

**Comment by slawr** [comment]
Passed the rebase and tests. I think this can be merged.

**Comment by slawr** [comment]
Is there anything standing in the way of this being merged?

**Comment by slawr** [comment]
@gunnarx this is the PR we discussed on the phone. It only affects R-Car.

**Pull request merged**
