### PR TITLE
meta-iot-web: Add new layer for iotivity-node support

### PR DESCRIPTION
**Pull request by rzr**
IoTivity NodeJS bindings ease development of IoT projects.
For more tips and details about using this, please check:
https://wiki.iotivity.org/automotive .

Current version is supporting IoTivity 1.2.0 from meta-oic.

[GDP-160] meta-genivi-ocf-demo merging

Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by zeenix** [comment]
@rzr Hey, shouldn't there be an associated meta-genivi-dev PR that makes use of this layer? I don't see much sense in merging something that's not going to be built.

**Comment by rzr** [comment]
Yes this is the 1st part, I am trying to get it shipped with this other change related to iotivity :
https://github.com/ostroproject/meta-iot-web/pull/30#issuecomment-279992361

this way changes into other layers will be minimal,

I will keep you posted.

**Comment by zeenix** [comment]
Cool, thanks for this effort. I'll close this for now. Please re-open when you're ready for a merge. :)

**Comment by rzr** [comment]
my comment was a parallel action, this PR is still valid and required for ongoing developments using iotivity-node

**Comment by zeenix** [comment]
@rzr why is it required to have these changes in master of main repository? I can imagine, it makes management easy for you but it's not a compelling enough reason to merge unused code/layer into g-d-p. Unless there is another rationale for merging this already that I'm missing?

**Comment by zeenix** [comment]
@rzr we can merge it into a branch if that helps you though so please let me know if that's the case.

**Comment by rzr** [comment]
Well it has to start somewhere into master tree before touching other layers, I making PR one after one to make sure they will be merged in the right order.

**Comment by zeenix** [comment]
@rzr Thanks but you don't need to worry about that. :) Just let me know the order after publishing the PRs and I'll ensure everything get's merged in order.

**Pull request closed without merging**
