### PR TITLE
Upgrade baseline to O-1.0 release

### PR DESCRIPTION
**Pull request by chbae**
Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

### CODE REVIEW

**Comment by slawr** [comment]
just fyi Tolkien is planning to release O-1.0 at the end of this week. If not then, it will be early next week.
No Genivi component updates. The third-party layers such as Poky and OE will update to the latest.

**Comment by chbae** [comment]
@slawr Thanks. Let's wait for O-1.0 release.

**Comment by gunnarx** [comment]
Looking good.  Restarted build for R-Car which failed because of a diskspace issue.

**Comment by gunnarx** [comment]
Currently working through some various trouble, such as the #136 / #137 issue which basically makes
There's a bunch of feature branches failing also, being disturbed by the same issues of course, but also mixed in with other issues.   I would hold on merging this a little while until everything feels more stable.

**Comment by gunnarx** [comment]
Build check:  R-Car failure is not a failure, it's the #136 / #137 issue.

**Comment by gunnarx** [comment]
Rebased.

**Comment by gunnarx** [comment]
We could switch this to O-1.0 tag now @chbae

**Comment by chbae** [comment]
I switched this to O-1.0

**Comment by gunnarx** [comment]
That's awesome, thanks @chbae.

**Comment by gunnarx** [comment]
Hmm, is this not merged yet.  @frznlogic - please do whenever you are ready.

By the way, Dragonboard when we had the issues with diskspace a few days ago.

**Comment by chbae** [comment]
Just rebase

**Comment by frznlogic** [comment]
Pulling in.

**Pull request merged**
