### PR TITLE
SDL: add meta-sdl as submodule

### PR DESCRIPTION
**Pull request by phongt**
Signed-off-by: Phong Tran <tranmanphong@gmail.com>

### CODE REVIEW

**Comment by gunnarx** [comment]
@phongt could you rebase this on latest master and resolve the merge conflict?
@zeenix commit log has more details now

By the way if you want to see how the HTML based example UI delivered with SDL looks like, just run this in shell:
```
git clone https://github.com/smartdevicelink/sdl_hmi/
cd sdl_hmi
google-chrome index.html
```
(Note that it only worked with Chrome browser in my test, not Firefox)

**Comment by zeenix** [comment]
@gunnarx Thanks. UI looks OK if not sure the panel on the right makes it possible to fit it on our small screen on the target but hopefully that can be easily disabled. We'll need to see it running on GDP to see if enough of the UI actually does something I guess.

**Comment by phongt** [comment]
@gunnarx I re based to master branch. I checked build ok with rpi3 environment.

**Comment by gunnarx** [comment]
I was informed today that this is the new and preferred generic demo HMI for SDL.

https://github.com/smartdevicelink/generic_hmi

But be aware that this one basically doesn't show anything until it's connected to something.
We should move to try that integration together with Chromium.

**Comment by phongt** [comment]
Update the new commit of meta-sdl.

1. Add bluez tools (new recipe) to runtime dependency 
2. Update smartdevicelink systemd service (Not enable as default, require and after bluetooth.service)
3. Update  of changing LICENSE of SDL

**Comment by gunnarx** [comment]
Need someone to put some work into integrating and testing the full system  HMI <-> Core (included meta-sdl) <-> Device.  But assuming we get the stuff working and can enable a demonstration, this will be merged into Master.  Thanks for keeping it updated @phongt

**Comment by gunnarx** [comment]
Rebased on master and pushed.  More checks are enabled this time around.

**Comment by gunnarx** [comment]
Build checks look good.  R-Car failure is a known unrelated issue.

**Comment by gunnarx** [comment]
Hi @phongt It has taken a while but we started working with this on a separate [feature branch](https://github.com/GENIVI/genivi-dev-platform/tree/feature_sdl).

**Comment by phongt** [comment]
@gunnarx  I fetched [feature_sdl](https://github.com/GENIVI/genivi-dev-platform/tree/feature_sdl) branch. It build failure. Seem like this commit  [1b9a7e06](https://github.com/GENIVI/meta-genivi-dev/commit/1b9a7e06b3917cd661b1402606982cf1b9e24df0). The patch 0001-V4-Free-up-2-address-bits-in-64bit-mode.patch is not available.

**Comment by gunnarx** [comment]
> @gunnarx I fetched feature_sdl branch. It build failure. Seem like this commit 1b9a7e06. The patch 0001-V4-Free-up-2-address-bits-in-64bit-mode.patch is not available.

Yes I agree that patch is bad.  Sorry we have not had time to update everywhere  (tickets, PR (2 of them), and team chat).   I rebased and took away the bad patch,  which was not meant to be included.  Unfortunately some other issues came up so I'll let you know if/when things are more proper.  Count on a lot of force-pushed updates on the feature branch until things are more stable.  (In fact, I can update this PR once they are).  Thanks.

**Comment by gunnarx** [comment]
@phongt OK, so feature_sdl branch builds ok (1b9028af610cad205712760983b100a0c1c4bcf9). Result seems OK.  We found it doesn't run automatically but that's expected since:  
sdl-core_4.1.0.bb:75:SYSTEMD_AUTO_ENABLE = "0"

**Comment by phongt** [comment]
Currently Smartdevicelink is not enable starting in default. Cause I think not all devices supported full Blu tooth yet. But it can be started  by command 'systemctl start smartdevicelink'.

**Comment by gunnarx** [comment]
> Currently Smartdevicelink is not enable starting in default. 
> Cause I think not all devices supported full Blu tooth yet.
I think, if building a system for a device that does not have Bluetooth, then you would not include the sdl-core feature in that system?

Anyway just to close the ticket on sdl-core integration we need to make it run by default, and we need to add that today (sprint ends today).  

Do you want a pull request SYSTEMD_AUTO_ENABLE = "1", or should we fix it locally?
I can fix it **temporarily** by : 
1. Add a .bbappend in our layer
or
2. Use [my own fork](https://github.com/gunnarx/meta-sdl)

I prefer it to enabled by default in meta-sdl.

**Comment by phongt** [comment]
@gunnarx  I updated the meta-sdl on the commit [ 7a47610 ](https://github.com/phongt/meta-sdl/commit/7a47610ba678f4ac4183ddc370281a66ff88989c) could you please update the commit of submodule  this pull request?Cause I am on traveling. Can't force push.

**Comment by gunnarx** [comment]
Yes 7a47610 has been includued in [generic_hmi branch/fork](https://github.com/gunnarx/meta-sdl/tree/generic_hmi) now, which is included from [feature_sdl](https://github.com/gunnarx/meta-sdl/tree/feature_sdl) here.

Work ongoing and I'll send a PR soon to meta-sdl but there seem to be required some more work after that.  I'd like to close this PR now since the layer is included on the feature branch.  Work is tracked on that branch and [tickets](https://at.projects.genivi.org/jira/browse/GDP-177) (see detailed tasks assigned to the Epic) better than in this comment section.

**Comment by gunnarx** [comment]
@phongt Same comment for this as for https://github.com/GENIVI/meta-genivi-dev/pull/67.  I can see that you saw the comment and closed that PR, so we do the same here.

**Comment by gunnarx** [comment]
Tracking the development on a [feature branch](https://github.com/GENIVI/genivi-dev-platform/tree/feature_sdl) and communication can happen on the [relevant tickets](https://at.projects.genivi.org/jira/browse/GDP-177) .

**Pull request closed without merging**
