### PR TITLE
Upgrade to Pyro

### PR DESCRIPTION
**Pull request by chbae**
[GDP-605] Upgrade base system to Yocto 2.3 / Pyro branch

### CODE REVIEW

**Comment by gunnarx** [comment]
Restarting build checks since there was some build agent issue. 

The agents deliberately have a minimal docker container, and the ping command (iputils-ping package) appears to be a new host dependency in pyro?   I updated the agent config so all agents should eventually be automatically updated, but let's see.

**Comment by gunnarx** [comment]
There is a relatively large rebase needed for this because of files moving around when we merged #103. I will try to do it now, and have you review the result.

Documenting the current PR commit, just so I don't forget and lose it later : https://github.com/GENIVI/genivi-dev-platform/pull/105/commits/61ce0f81e7ea3a473629e64b37e844e24060f0c4

**Comment by chbae** [comment]
I'll rebase it tomorrow :) Thanks for the notification.

**Comment by gunnarx** [comment]
@chbae.  I created #106 to test the (complicated) merge.  The build failure listed here on R-Car seems like a real failure (I think?)  I had the same when test building this PR separately.  Do you have some idea?  If you can find a fix, maybe we'll just cherry-pick it - I probably don't want to go through the messy merge again.

**Comment by slawr** [comment]
R-Car has no pyro support yet, so a build failure would not be a surprise. Strange the meta-linaro errors relate to missing files though, assuming it refs patches that are actually in the layer.

**Comment by chbae** [comment]
I can't produce error message in qemux86-64.
@gunnarx Could you check this error?

**Comment by gunnarx** [comment]
I've seen this before but I'm not sure what caused it @chbae.  In any case it seems to have not happened on my #106.   We are too much out of sync now to compare because I can see you rebased on top of latest master (impressive work), but I have not yet done that on #106 and it looks like we ended up with some small differences also.

Just to compare more easily I'll bring #106 up to date by cherry-picking the latest commits on top of it instead.  I notice some differences in audiomanager specifically.  

The other differences I see, and this is to fit the new naming structure.  

You created
meta-genivi-dev/meta-genivi-dev/recipes-graphics/mesa/mesa_%.bbappend

but if we are following the new convention to match the .bb and .bbappend it would instead be:
meta-genivi-dev/poky/meta/recipes-graphics/mesa/mesa_%.bbappend

Similarly you have:
meta-genivi-dev/meta-genivi-dev/recipes-devtools/erlang/erlang-native_%.bbappend

but I have the same file here:
meta-genivi-dev/meta-erlang/recipes-devtools/erlang/erlang-native_%.bbappend
and of course that sublayers is also added to the bblayer template(s).

**Comment by chbae** [comment]
@gunnarx  Ok. At first, I'll change recipe location as our policy.

**Comment by chbae** [comment]
@gunnarx please review my changes :)

**Comment by slawr** [comment]
Hi, 

Which is the correct integration branch for me to develop R-Car Gen 3 support against?
The push branch for PR 105 or 106?

To reduce re-work I'm doing the R-Car Genivi YBSP re-org (split YP and meta-ivi support into separate reps) at the same time so will need to take into account the GDP layer reorg.

Regards

Steve

**Comment by DunderRoffe** [comment]
> Only pushing this for build tests and for @chbae to look at.
>
> I created a merge commit (see commit message for more details) where the new bbappend added in #105
> are also moved to new locations. It's easy to miss extra files like patches and such, so I expect probably some build errors here.

@slawr judging from @gunnarx statement in PR-106 I am assuming that you should work in PR-105 i.e. this PR.

**Comment by chbae** [comment]
@slawr Please use PR #105 :)

**Comment by chbae** [comment]
Rebased.

**Comment by gunnarx** [comment]
I cleaned up the remaining failure(s) and it looks like this:

ERROR: renesas-rcar-gen3/meta-rcar-gen3/recipes-bsp/u-boot/u-boot_2015.04.bb: 
     This recipe does not have the LICENSE field set (u-boot)

Maybe LICENSE field was optional before and mandatory now?

@slawr - could you look at that?

----

Before that there are these warnings:

WARNING:  Unable to get checksum for ... SRC_URI entry 0002-binutils-cross-Do-not-generate-linker-script-directo.patch -- file could not be found

Same warning 2 more times - these include the same .inc files and therefore the same patch file
meta-linaro/.../binutils-crosssdk_linaro-2.25.bb and
meta-linaro/.../binutils-cross_linaro-2.25.bb:

Through a quick discussion in #yocto I confirmed it is "file not found" meaning the patch file itself is not found to be able to checksum it  It's not about defining SRC_URI checksum, it's about finding the file at all... 

If the patch file is not found, it should lead to a  build error, at least later.  But right now the build stops immediately on "Can't parse recipe" for u-boot so I assume later errors might be masked.

**Comment by gunnarx** [comment]
Apparently meta-linaro has a fix in https://github.com/linaro-home/meta-linaro/commit/6665c774a8dfde14a64ec56452f5c4bc20508725 in June.   

I think I was fooling myself into thinking we had a matching meta-linaro/poky, even if it was old, but of course not -- poky has been updated in this PR to match pyro and match all the other layers, whereas meta-linaro has not yet.

So clearly it's just about the work to do the necessary updates so I'll leave this if @slawr can take over?

**Comment by slawr** [comment]
> ERROR: renesas-rcar-gen3/meta-rcar-gen3/recipes-bsp/u-boot/u-boot_2015.04.bb:
> This recipe does not have the LICENSE field set (u-boot)
> 
> Maybe LICENSE field was optional before and mandatory now?

It's caused by the u-boot include splitting into two files in Pyro. 
The new file provides the LICENSE info.

> 
> @slawr - could you look at that?

I already have a local fix to supply the missing file. I could give it you but 
I wonder about the value. There does not seem much point building 
R-Car until I push the Pyro YBSP?

Status on that is I have Pyro core-image-weston built and am about to do
tests. So I expect to publish soon. Once that is done meta-ivi and GDP should 
follow quickly.

**Comment by slawr** [comment]
> Apparently meta-linaro has a fix in linaro-home/meta-linaro@6665c77 in June.

@gunnarx Thanks for the hint. I have that in my local feature tree which explains why I had not seen it.

> 
> I think I was fooling myself into thinking we had a matching meta-linaro/poky, even if it was old, but of course not -- poky has been updated in this PR to match pyro and match all the other layers, whereas meta-linaro has not yet.
> 
> So clearly it's just about the work to do the necessary updates so I'll leave this if @slawr can take over?

Sure. Update will come with R-Car Pyro support.

GDP changes will be:
1. Adopt Pyro meta-linaro and YBSP branches.
2. Switch to renamed Gen 3 YBSP
3. Adapt to Genivi YBSP being split into YBSP and meta-ivi layer, i.e. add meta-ivi-renesas
4. Not needed initially but have possibility to later move Gen 3 GDP machine recipe modifiers (foo_m3uclb) into GDP bsp area.

**Comment by gunnarx** [comment]
> I already have a local fix to supply the missing file. I could give it you but I wonder about the value. There does not seem much point building R-Car until I push the Pyro YBSP?

I feel that as soon as we have something that roughly works OK for all platforms this PR can be merged to master.  I would hope we don't need to delay it too much longer.  So I would accept a staged approach with first a quick-fix, and additional R-Car BSP improvements later applied to master, but it's up to you how you prefer to do it (as long as it's not too far from completion).

**Comment by slawr** [comment]
> I feel that as soon as we have something that roughly works OK for all platforms this PR can be merged to master. I would hope we don't need to delay it too much longer. So I would accept a staged approach with first a quick-fix, and additional R-Car BSP improvements later applied to master, but it's up to you how you prefer to do it (as long as it's not too far from completion).

That was what I was planning as well. First operational beta, followed possibly by some improvements. There will be a subsequent YBSP version update end of the month that I will be merging anyway.

Good news is that core-image-weston boots weston. So I'm now cleaning up and aiming for a release early next week. meta-ivi and GDP should follow quickly with that milestone achieved.

**Comment by gunnarx** [comment]
OK, so we are almost there now.  But there is something broken with the PR build plugin at the moment.  (Perhaps GitHub has changed some API).  In any case we want to get some images out to test so I pushed this to a branch and temporarily set the Release builds to build the pyro branch.  From there we can d/l and test.

**Comment by chbae** [comment]
Merged in https://github.com/GENIVI/genivi-dev-platform/pull/129

**Pull request closed without merging**
