### PR TITLE
meta-oic: Update to current version

### PR DESCRIPTION
**Pull request by rzr**
Bug: https://at.projects.genivi.org/jira/browse/GOCF-27
Change-Id: I7a0d52a1e9d9f906fe2c70f76421e21cdbc2d82a
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by chbae** [comment]
I'll test tomorrorw :) Sorry for late.

**Comment by rzr** [comment]
Once merged I'll provide an other patch to test it on device

**Comment by iamsanjeev** [comment]
Genivi OCF CES 2017 Automotive demo will be easier with this merge. Else we will have to do this manually.
Request to merge this.

**Comment by rzr** [comment]
Ask me on issues or support, I will prepare 1.2.x recipes after we validate current version

**Comment by gunnarx** [comment]
+1  
If both Sanjeev and Phil say this is good then I doubt anyone else has a better view.

By the way, the PR builds fine:
https://go.genivi.org/go/pipelines/GDP-Yocto-QEMU_x86-64-GITHUB-PR/22/build/1
https://go.genivi.org/go/pipelines/GDP-Yocto-PORTER-GITHUB-PR/24/build/1
https://go.genivi.org/go/pipelines/GDP-Yocto-RPI2-GITHUB-PR/21/build/1
https://go.genivi.org/go/pipelines/GDP-Yocto-MINNOWBOARD-GITHUB-PR/23/build/1
(I don't know why build results were not reported here in the PR on GitHub...  We will have to look at what changed.)

@zeenix - this should be safe as far as I can see.  The meta-oic functionality is quite separated - recommend merging.  

(Or if you prefer you can work with a release branch for the final QA but there's some time still.  In any case I think we should bring this into master if it's needed by the OIC/IOtivity work)

**Comment by zeenix** [comment]
Thanks @gunnarx . @chbae Did you manage to test? I'll merge it tomorrow anyway if no issues are reported but I'll feel much better if someone tests it first.

**Comment by zeenix** [comment]
Merging.

**Comment by rzr** [comment]
Thanks, can you please now review:
https://github.com/GENIVI/meta-genivi-dev/pull/47

**Pull request merged**
