### PR TITLE
Dragonboard chromium pyro

### PR DESCRIPTION
**Pull request by gunnarx**
We had this open before but closed again.  It's now up to date with master (pyro branch etc).

I'm placing it here for comparison with chromium_pyro.  Please feel free to review it for commit content/format. I suggest to not merge until testing is concluded however.

### CODE REVIEW

**Comment by gunnarx** [comment]
Hmm, I could have put this as a PR towards chromium_pyro branch for clarity, but to be clear the only dragonboard-related diff is the last commit: e621bec5a

**Comment by gunnarx** [comment]
Cherry-picked the relevant commit onto feature_sdl_pyro this time (since that will likely supersede the chromium branch anyway), but just as before the PR shows the difference towards master.  (The last commit is the relevant one)

**Comment by frznlogic** [comment]
Rebased and put the commit on top of master. Waiting for builds to finish to see results.

**Comment by gunnarx** [comment]
I have a better commit comment for this.  Let me push & merge it when we confirm.

**Comment by frznlogic** [comment]
Compilation is confirmed I would say

**Comment by frznlogic** [comment]
Merging this PR as it's needed.

**Pull request merged**
