### PR TITLE
meta-ivi update (rocko branch)

### PR DESCRIPTION
**Pull request by gunnarx**
Note: includes the old hardening flags change finally.  Functionality ought to be tested.
A few other component updates -- see full commit msg

### CODE REVIEW

**Comment by gunnarx** [comment]
iotivity failing, trying to bump meta-oic to latest first

**Comment by gunnarx** [comment]
Looks like iotivity has lots of updates upstream.  Waiting for meta-oic to update also.

**Comment by gunnarx** [comment]
> The meta-gplv2 commit message seems to have been truncated. Incomplete first line and no body.

Thanks, should be fixed before merging

**Comment by gunnarx** [comment]
Just rebased on latest master (nothing fixed, expect to be failing still)

**Comment by slawr** [comment]
Noticed that meta-ivi was out of date earlier setting up a sanity building of the R-Car Yocto BSP v3.9.0 update. I decided to stay with P-0.1 for the test as that was what master uses, but good to see I don't need to send a PR to update later :+1:

**Comment by gunnarx** [comment]
Rebased on master for good measure. Updated meta-qcom to at least remove gpsd build failure on that platform.  Remaining failure right now is iotivity in combination with hardening flags.

**Pull request closed without merging**
