### PR TITLE
renesas: add renesas r-car gen 2 support for GDP11

### PR DESCRIPTION
**Pull request by slawr**
Upgrade to meta-renesas YP 2.1 release.
Enable porter/silk board support for GDP Master
branch in init.sh again.

### CODE REVIEW

**Comment by tom--pollard** [comment]
Building as we speak :)

**Comment by tom--pollard** [comment]
Built successfully, deploying.

**Comment by RobertAJMarshall** [comment]
Built and deployed here - not hearing any sound though, I will open a ticket

**Comment by tom--pollard** [comment]
Added a comment to the ticket https://at.projects.genivi.org/jira/browse/GDP-365 re audio. Testing a silk build now

**Comment by RobertAJMarshall** [comment]
Silk builds ok for me

**Comment by tom--pollard** [comment]
Tested on both boards, not seeing anything new beyond the already recorded issues. +1 from me. (Maybe the addition of [GDP-213] GDP Master support for Renesas boards in the commit body or the individual silk/porter tickets for to please the jira gods...)

**Comment by slawr** [comment]
Gunnar made a good comment on PR #34. Ideally the local.conf change from there would be pulled as well - see my reply as to why. Although it looks like you have done your builds so perhaps too late for this round.

**Comment by tom--pollard** [comment]
@slawr Feel free to add that commit to this PR :) I have all the build envs available if I need to sanity check the addition...

**Comment by slawr** [comment]
@tom--pollard ok wasn't sure what github allowed in terms of updates. Done. I'll close #34 as superseded by this one

**Comment by tom--pollard** [comment]
@slawr sorry to be pedantic but could you add a signed offline to the first commit? Thanks :)

**Comment by slawr** [comment]
@tom--pollard hmm the github PR compare mechanism doesn't exactly make that detail clear. Which specific comment are your referring to?

**Comment by slawr** [comment]
@tom--pollard if your referring to "renesas: add renesas r-car gen 2 support for GDP11" then it comes via my git rep, rather than a patch file with the other commit (because it was taken from the earlier PR), hence no sign-off. Similar to many of your own commits or am I missing something?

**Comment by tom--pollard** [comment]
@slawr Normally I'd expect that commit to have a signed off line in the message (might be confusing each other here!) If it's a PR with multiple commits then the top level comment can hold the sign-off, as long as the merge commit is preserved.

**Comment by slawr** [comment]
@tom--pollard I think (hope :) ) I understand you. You're saying you would like commit 674d744 (renesas: add renesas r-car gen 2 support for GDP11) to have a signed off line, like the other commit. Is that right?

My point was that the two commits are products of different workflows. 674d744 was formed using the github pr mechanism of branch comparisons. The commit to my fork was not made with -s to add a signed off line (the default in git). The other commit was cherry-picked from the earlier PR #34 for GDP-10 using git format-patch and applied to my fork with git am. In that case as it was a patch process I added the signed off line. Hence why one is signed-off and the other isn't. My final point was that as far as I am aware Genivi was not requiring a sign off on git commit and I can see this seems to be the case for the majority of commits to the GDP git rep. For example Robert's recent commit [8480c](https://github.com/GENIVI/genivi-dev-platform/commit/8480c94f50918fe554b33a62c18c762546663316) or your commit [17e6](https://github.com/GENIVI/genivi-dev-platform/commit/17e644c8e6f06379a6043290709950989d4b3a9b).

I can add a sign off if you really want it but I would need to recreate the commit as adding the sign-off is going to change it. Also I would suggest the need for a sign off in a git commit workflow would need to be made clear somewhere else a lot of people are going to have this rework.

**Comment by tom--pollard** [comment]
@slawr I honestly don't know the in's and out's of what Genivi require (in terms of my commits not having sign-offs, I've raised that before re maintainers requirement to use it and the answer wasn't very helpful...)  I understand what you mean with traditional patch-process vs github fork workflow, maybe it should be discussed in the next GDP call for clarification. Sorry for any confusion on the matter.

**Comment by slawr** [comment]
@tom--pollard No problem at all Tom. It's not easy for you to detect what workflow was used and I think sign off on a patch makes sense. Yes I would say bring it up. It could do with some clarification and normalisation across the alliance.

**Pull request merged**
