### PR TITLE
meta-genivi-dev: Update to c96fd40

### PR DESCRIPTION
**Pull request by leon-anavi**
Update layer meta-genivi-dev and deploy bash script sota-demo-reset.sh.

[SWM-10] Reset SOTA Demo
[SWM-9] Move GENIVI SWM DB away from /tmp

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Comment by gunnarx** [comment]
@leon-anavi.  Uh, what's going on with the  commit summary?   
Remember the principle of a good programmer: "Don't repeat yourself" :-)

We recommend using [this script](https://github.com/GENIVI/genivi-dev-platform/blob/master/git-submodule-bump) which gives a shortlog of the changes in the submodule.  You can then amend the commit and add bug references (they are good).

The [Rules for commit messages](https://at.projects.genivi.org/wiki/display/PROJ/Rules+for+Commit+Messages) have been updated if you're interested.

Thanks.

**Comment by chbae** [comment]
@gunnarx, @leon-anavi 
I thought that it's better maintainers to change meta-genivi-dev's commit. However, if developers require to change other meta-layers or configuration files in genivi-dev-platform, they can create PR in genivi-dev-platform. How about your opinion? Thanks

**Comment by leon-anavi** [comment]
Hi @gunnarx, thank you for the quick feedback. I used git-submodule-bump but indeed I have overwhelmed the description. I have now updated it.

**Comment by gunnarx** [comment]
I stopped the build checks (they report as "fail" when stopped) since the PR needs update anyhow.
We have some other PRs that can use the build capacity now.

**Comment by gunnarx** [comment]
@leon-anavi Did you push the changes?  It looks the same here.

**Comment by gunnarx** [comment]
@chbae 
> I thought that it's better maintainers to change meta-genivi-dev's commit. 
>However, if developers require to change other meta-layers or configuration 
> files in genivi-dev-platform, they can create PR in genivi-dev-platform. 
> How about your opinion? Thanks

I think I see what you mean but I am not sure what we gain from it?   If you want to wait we can always choose to wait or not approve the PR from the developer.  But sometimes it is good to have a quick update and also to be reminded something has changed.

In principle I see no problem with a developer asking for a meta-genivi-dev update.  It is just a way to ask for their functionality to be included in the platform.  Just like any project.  Why more complicated just because we have submodules and layers?

In fact, I have decided we should integrate meta-genivi-dev into genivi-dev-platform (as we have discussed many times before) to speed things up.   So this will no longer be a question.

**Comment by leon-anavi** [comment]
@gunnarx, yes, I pushed it. It is the same commit but with shorter description: https://github.com/GENIVI/genivi-dev-platform/pull/87/commits/c841bcf98b1c7f13bdfdae96bbd851e4d1768c90

**Comment by gunnarx** [comment]
@leon-anavi  Let me explain again. I can see you removed some description.  That's not what I meant.  I said **commit summary**, I mean the first line.   The script prepends the name of the submodule, so it's easy to make it double by mistake.  If it happens you amend and fix.   But 3 times!?  Never seen it :-)

But you also do not have the shortlog of the commit changes inside meta-genivi-dev so the value of the script is not there.

meta-genivi-dev: Update to c96fd40

[Your explanation, if you feel you need it.  Very brief since details are in the submodule]

<hash> description  <--- the "shortlog"
<hash> description
<hash> description

[GDP-xxx] description

Sign-off.

**Comment by leon-anavi** [comment]
ops, sorry. I lost shape after going out on a vacation for a week :) Fixed.

**Comment by gunnarx** [comment]
And fixed again. By the way, warning that you are providing the PR from your master, which means GitHub allows the PR to be updated by pushing to that branch.   I can now push changes to your *master* branch (which I just did).  If this is a concern, use a separate branch for PRs.

**Comment by gunnarx** [comment]
Thanks for the PR.  Build checks should run eventually when there is capacity.

**Comment by leon-anavi** [comment]
Thank you.

**Comment by chbae** [comment]
> In fact, I have decided we should integrate meta-genivi-dev into genivi-dev-platform (as we have discussed many times before) to speed things up. So this will no longer be a question.

Ok. That sounds good. I agree with you.

**Comment by gunnarx** [comment]
This should be all OK and we're bumping m-g-d additionally soon to include a reworked version of chromium branch. Merging.

**Pull request merged**
