### PR TITLE
Upgrade to rocko

### PR DESCRIPTION
**Pull request by chbae**

### CODE REVIEW

**Comment by slawr** [comment]
Hi Changhyeok,

How does this relate to @gunnarx PR #173? I plan to send commits to update the R-Car submodules and need to know which PR is the working branch for the G14 update?

btw just to let you know the 14.0.0 (P-1.0) release of the Yocto Baseline should be made this work. Updates to a few components and revs to current poky, mta-oe and meta-gplv2.

Regards

Steve

**Comment by gunnarx** [comment]
Any input is good input. I will compare and/or merge this within the next few days but I am “supposed” to be free from work tomorrow .  :) 
Just looking at the commits it looks like Changhyeok built on top of my commits and fixed a bunch of errors. Thanks for your work so far @chbae

**Comment by slawr** [comment]
> @slawr which commit is that by the way?
Hmm was struggling to find it again.. but did fine one instance in the meta-intel update. Don't know if that is the only one. Was just checking what commit msg format ppl were using.
Also noticed one commit (poky or meta-oe I think) that had no signed-off.

I have the R-Car rev pretty much done for YBSP v3.4.0. Basic clone, init.sh and then bitbake -p works without error. So that will drop in the morning.

**Comment by slawr** [comment]
@gunnarx, @chbae I have just push a PR to Changyeok's git rep to add R-Car Gen 3 support. Please merge it into this work.

**Comment by slawr** [comment]
I successfully built this with my PR for R-Car M3 Starter Kit. I'll test it today.

**Comment by slawr** [comment]
What runtime results did you get in your tests?

I find the HMI is not starting on M3 SK. 
I can however run EGLWLMockNavigation app fine so the gfx stack seems to be functioning.
If I manually try to start the HMI I get the following output:
```
root@m3ulcb:~# /opt/gdp-hmi/bin/gdp-hmi -platform wayland
Using Wayland-EGL
Successfully registered object
Error while registering service on  "qt_default_system_bus"
"org.freedesktop.DBus.Error.AccessDenied"
"Connection \":1.17\" is not allowed to own the service \"org.genivi.development.platform.HMI\" due to security policies in the configuration file"
LACO [ Debug ] Debug: ilm_getScreenIDs - success. number of screens = 1                                                                                    | layercontroller.cpp:257
LACO [ Debug ] Debug: Screen ID[0] = 0                                                                                                                     | layercontroller.cpp:260
LACO [ Info  ] Info: initScreen() - screen size = 1920 x 1080                                                                                              | layercontroller.cpp:277
NOTE: This GSX library has the time limitation by reason of an evaluation module.
LACO [ Debug ] Debug: createLayer (id = 0) - success (1920 x 1080)                                                                                         | layercontroller.cpp:371
LACO [ Debug ] Debug: createLayer (id = 3137) - success (1920 x 1080)                                                                                      | layercontroller.cpp:371
layerid=0 is already used.
LACO [ Error ] Error: createLayer (id = 0) - failed                                                                                                        | layercontroller.cpp:368
Cannot set pointer or touch focus for multiple surfaces
layerid=0 is already used.
```

The HMI main menu will come up but the HMI is not very operational.

**Comment by gunnarx** [comment]
This is now obsolete since it is included in #176 and #177 so to simplify things I think we can close it.
We discussed today on BIT call and **slawr** bug report above will be put into JIRA for further tracking.

**Comment by gunnarx** [comment]
Thank @chbae for your contribution.  Hope to merge it soon, via #177, but we need to work out a few issues.

**Pull request closed without merging**
