### PR TITLE
meta-rust: Update to latest git krogoth

### PR DESCRIPTION
**Pull request by leon-anavi**
The latest version of meta-rust in branch Krogoth
contains a bug fix for building a toolchain
installer (with -c populate_sdk).

[GDP-539] populate_sdk fails on Raspberry Pi 3

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Comment by chbae** [comment]
This patch should be merged with https://github.com/GENIVI/meta-genivi-dev/pull/51.

**Comment by chbae** [comment]
Successfully built with https://github.com/GENIVI/meta-genivi-dev/pull/51.

I got the below error but it's known issue.

ERROR: genivi-dev-platform-1.3+snapshot-20170102-r0 do_populate_sdk: Taskhash mismatch 9163f510bbe65dc436e2ab7584ce245d verses 845798b1a20fa388156e2bb2062933ba for /home/changhyeok.bae/work/ivi/genivi-dev-platform/gdp-src-build/../meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bb.do_populate_sdk
ERROR: Taskhash mismatch 9163f510bbe65dc436e2ab7584ce245d verses 845798b1a20fa388156e2bb2062933ba for /home/changhyeok.bae/work/ivi/genivi-dev-platform/gdp-src-build/../meta-genivi-dev/meta-genivi-dev/recipes-dev-platform/images/genivi-dev-platform.bb.do_populate_sdk

**Comment by chbae** [comment]
@leon-anavi 

I merged https://github.com/GENIVI/meta-genivi-dev/pull/51. Could you apply meta-genivi-dev commit hash value in this PR?

Thanks
Changhyeok

**Comment by leon-anavi** [comment]
Hi @chbae,

Thank you. Yes, I will apply the update of meta-genivi-dev right away.

Best regards,
Leon

**Comment by leon-anavi** [comment]
Hi @chbae,

Following your recommendations I have included an update of meta-genivi-dev as part of this PR.

Thanks,
Leon

**Pull request merged**
