### PR TITLE
Rocko combined + chromium

### PR DESCRIPTION
**Pull request by gunnarx**
Yet another...  (To remember the build history of #175 in isolation it's better to keep that one unchanged instead of updating it).

As the title suggests, this one contains #175 + Chromium (i.e. #174).  More specifically, the two unique Chromium commits were rebased on top of #175, so that we end up with:

chbae rocko upgrade + stephen's r-car upgrade + jaragunde chromium upgrades (in that order)

(It's therefore expected to have the same issues as the others with regards to compilation on some targets)

### CODE REVIEW

**Comment by gunnarx** [comment]
Update: Also here added the CI script fix aa6a85f for a bug that might be responsible for the R-Car failed build in CI

**Comment by gunnarx** [comment]
Rebased including the two latest fixes from @jaragunde

**Comment by frznlogic** [comment]
Jira ticket on the problems with layer id in gdp-new-hmi together with wayland-ivi-extensions: 
https://at.projects.genivi.org/jira/browse/GDP-778

**Comment by gunnarx** [comment]
Now that compilation works on all, @jaragunde @slawr @chbae and all - please use the JIRA ticket that Oscar posted for run-time results (and solutions to the problem).

**Comment by gunnarx** [comment]
Added on one commit: Mirza's SDK fix that removes qtwebkit also from SDK (already removed from image).

**Comment by gunnarx** [comment]
Rebased on master, primarily to get the new test support.  (The QEMU CI build has already been switched over, so the PR must be based on that or the CI build will fail).

Commit a77969bb63421179986d22fbf58ba77b4c3f0456 that modifies wayland-ivi-extension bbappend conflicts since that bbappend has been removed in commit ed89b206d36c9542bf8e20096466476ab3582e7d on master.  
Conflict was resolved by omitting this commit.  A second reason is that I believe the problem addressed by a77969bb63421179986d22fbf58ba77b4c3f0456 is also fixed upstream in wayland-ivi-extension by now.

**Comment by gunnarx** [comment]
Everything looking good on the build checks but on a clean build (no sstate cache) there is a transaction check conflict between these packages:

15:30:26.506 Error: Transaction check error:
15:30:26.506   file /usr/share/polkit-1/rules.d conflicts between attempted installs of systemd-1:234-r0.core2_64 and polkit-0.113-r0.core2_64

**Comment by gunnarx** [comment]
I think it's better to move this to a feature/development branch now, it's easier to manage and other people's development & testing efforts could also shift over to the branch.  It should be fairly close to merging to master.  I created https://github.com/GENIVI/genivi-dev-platform/tree/rocko for this.

**Comment by gunnarx** [comment]
Cleaned up WIP commits, pushed to rocko feature branch (and this PR).

**Comment by gunnarx** [comment]
@chbae First - thanks for your early work on this.  We had to work through SDK build failure and some other HMI issues.  Would you have any opportunity to test [this](https://github.com/GENIVI/genivi-dev-platform/tree/rocko) on some hardware?

**Comment by slawr** [comment]
@gunnarx latest code tested as requested. Results written up in GDP-778. Summary is HMI is improved but still unstable. I'll not return to the R-Car YBSP v3.7.0 update PR.

**Comment by gunnarx** [comment]
Continued on [rocko branch](https://github.com/genivi/genivi-dev-platform/tree/rocko)

**Comment by gunnarx** [comment]
(update): rocko branch has since been merged to master.

**Pull request closed without merging**
