### PR TITLE
meta-linaro: Update to pyro branch

### PR DESCRIPTION
**Pull request by gunnarx**
Let's see how this goes.   Thanks to @slawr.

9bc4b59 meta-linaro: move genericarmv8*.conf machines
a7131d1 optee-client: Respect LDFLAGS set from OE build
5023898 gcc-cross{-initial}.inc: import from OE-core/master
388427b gcc-linaro: add 7.1.1-2017.05
6665c77 binutils: update binutils-cross specific patch to follow oe-core
90fc7a4 binutils: sync patch with OE-core
51d0de5 idlestat: uprev to 0.8 release
fe7980c optee: uprev client/os/test to 2.4.0
b18663a external-linaro-toolchain: add missing PKGV statements
8cc5866 tcmode-external-linaro: also blacklist gcc-runtime
3c63974 insane: rewrite the expanded-d test as a QAPKGTEST
21d4b94 insane: add QAPKGTEST, a package-wide equivilant to QAPATHTEST
6811da9 insane: factor out the test matrix processing
fc69634 insane: fix expanded-d test
0ee469d insane: Add aarch64 baremetal mappings to the QA arch test
df5639b insane.bbclass:buildpaths: open() file with 'rb'
f6df34b insane.bbclass: fix package_qa_check_arch() for mips64-o32
1bd8b91 insane: display names instead of ELF machine numbers
0881d0e insane.bbclass: Add mipsisa{32, 64}r6{el, }
300f12b insane.bbclass: Additional "mips" and "mipsel" machine definitions
0954d98 sanity: make license QA failures fatal again
3d2e4bf insane: improve package_qa_clean_path
2cfdad8 insane: only check ${S} exists if we had sources to fetch
afe67c7 insane: Add mechanism to extend QA machine information from BSP layer
5c66c1c meta-linaro-integration: recipes-overlayed: add kselftests
f61cfbb tcmode-external-linaro: blacklist toolchain recipes
a43d35b Revert "flex: overlay old recipe"
31239c9 ldconfig-native: remove local copy in favor of oe-core one
67974e9 external-linaro-toolchain: fix packaging for 6.3-2017.02
578578c gcc-linaro: replace 6.2 with 6.3
27ccce6 optee: uprev client/os/test to 2.3.0
c8328b0 gator: fix linking, try 2
531e950 gator: update to 5.22 and fix build
a85d484 binutils linaro-2.27: add missing patch
dca3d3f binutils-linaro 2.25: add missing patch
da876cf Revert "gdb 7.12 bbappend: backport armv8b buildfix"
9a682b7 linux-image-common: fwts is not available for armv7a, so remove it from armv7a
a608b11 ftws: overlay to add armv7a support
e752dfa gdb 7.12 bbappend: backport armv8b buildfix
eb86f6d flex: overlay old recipe
eefbf53 fwts: drop
992eaa0 optee-test: add a patch fix build failure with GCC 6
05eae57 optee-os: fix build failure with GCC 6
d13fbec binutils-crosssdk: match OE-Core, use SDK_SYS suffix instead of SDK/TARGET_ARCH
8ef3cd7 binutils: add lost relocatable_sdk.patch used by crosssdk 2.27 recipe
1b666f2 recipes: fix SRC_URI, as releases.linaro.org moved YY.MM dirs into archive
db09d02 external-linaro-toolchain: sync PROVIDES and PACKAGES with OE-core
c18a601 gcc: add linaro 6.2-2016.11
af87210 optee-client: respect OE's ${libdir}
5132a5e binutils: add linaro-2.27

This layer update had been missed in some previous Renesas & pyro branch
updates.  This updates also gcc, hopefully taking care of internal
compiler bugs that have been troubling us.

As of today 9bc4b59 is one commit away from the tip of the branch but I
decided it was likely not relevant, and want to align with what has been
tested by Stephen Lawrence.

### CODE REVIEW

**Comment by slawr** [comment]
Just a comment, but is it supposed to be only checking on Dragonboard?

**Comment by gunnarx** [comment]
@slawr  Checks are reported as soon as the build is actually started.  They might not yet be started if the build agents are busy.  That's simply how it works :-)

**Comment by slawr** [comment]
@gunnarx ok. I forgot that then if I ever knew. Carry-on :) Thanks for the PR

**Comment by gunnarx** [comment]
We have been really bad at using ticket references lately.  Fixed and pushed again

**Pull request merged**
