### PR TITLE
Minor cleanups in renesas local.conf templates

### PR DESCRIPTION
**Pull request by mirzak**

### CODE REVIEW

**Comment by gunnarx** [comment]
Looks good to remove some duplication, but I'll defer to slawr for further review.

**Comment by slawr** [comment]
> But this all gen2 boards right? Which are not effect by my patch at all because the change was moved to a file that is only common to "gen3" boards (renesas-rcar-gen3.local.inc).

Nope. Gen 3 SoCs = e.g H3, M3, D3, V3H. H3/M3 Starter Kit and H3/M3/M3N Salvator-X(S) are all Gen 3 boards.

**Comment by mirzak** [comment]
Ok, will drop the second patch.

**Comment by gunnarx** [comment]
@mirzak  Should 41613a3 be dropped completely then?  Or did you already adjust this...  
(I can drop it when merging, as long as I know)

**Comment by mirzak** [comment]
Yeah, 41613a3 can completely be dropped. You can do that when merging. But still need ACK from @slawr on the other commit.

**Comment by gunnarx** [comment]
@slawr can I merge the 5ac77d6 commit (only)?

**Comment by slawr** [comment]
Hi, had to concentrate on some topics. Plan to catch up on some things including this in the next day or two. I need to check my notes to see why I added it to the per machine conf.

Has it been tested to check the correct value is set without it?

**Comment by gunnarx** [comment]
> Has it been tested to check the correct value is set without it?

Not sure.  How can we test it?

**Comment by slawr** [comment]
> Not sure. How can we test it?

It's a variable so you can just bitbake environment dump to check that var is set correctly without that line - that's Mirza's hypothesis that it is a duplication. So check the hypothesis.

If you wanted to go onto "belt and braces" you could sanity test an M3 SK build.

**Comment by mirzak** [comment]
I did do a sanity check of the variables and a build of the M3 SK. I am not throwing out pull-requests without at least some sanity testing :).

We should have also gotten a build from our CI, but can only see minnowboard though.

**Comment by mirzak** [comment]
SOC_FAMILY is already setup in meta-renesas,

https://github.com/renesas-rcar/meta-renesas/blob/rocko/meta-rcar-gen3/conf/machine/m3ulcb.conf#L5
https://github.com/renesas-rcar/meta-renesas/blob/rocko/meta-rcar-gen3/conf/machine/h3ulcb.conf#L5

so yeah setting MACHINE = "m3ulcb", will result in SOC_FAMILY being set to what is defined in m3ulcb.conf

**Comment by mirzak** [comment]
Updated PR where I have dropped the second commit as agreed.

**Comment by slawr** [comment]
For the life of me I can't find the review "approve" button.

**Comment by gunnarx** [comment]
I'll take that as approval :)

**Pull request merged**
