### PR TITLE
WIP: bump Chromium version

### PR DESCRIPTION
**Pull request by jaragunde**
This pull request bumps the version of Chromium from 53 to 63.

Instead of using the latest version of the Chromium recipes from the meta-browser layer, it uses a different one from [meta-lgsvl-browser](https://github.com/lgsvl/meta-lgsvl-browser), who maintain a newer version of Chromium with the Ozone/Wayland backend that we were using in previous releases. The version of Chromium-Wayland provided by meta-browser doesn't support the IVI shell so I would like to skip it for this release and reconsider for the next one.

This couple of patches have been tested with Raspberry Pi 3 and they should work with 2. Builds for R-Car gen 3 are known to be crashing at this point.

TODO:
* fix R-Car gen 3 build
* test minnowboard
* test dragonboard
* rebase multi-seat patches (if time permits)

### CODE REVIEW

**Comment by jaragunde** [comment]
Just to be clear, I'm opening this PR to give visibility to this work so others can try it or build upon it, but I'm not requesting to merge it yet. Also, I'm taking a couple of weeks off so I won't be updating it yet.

**Comment by jaragunde** [comment]
For reference, this is the current error I'm facing when building for R-Car gen 3:
```
FAILED: obj/third_party/libvpx/libvpx/fdct32x32_neon.o 
aarch64-poky-linux-gcc  -march=armv8-a -mtune=cortex-a57.cortex-a53 --sysroot=/home/igalia/jaragunde/genivi-salvator-x/gdp-src-build/tmp/work/aarch64-poky-linux/chromium-lge/63.0.3239.132.lge.1-r0/recipe-sysroot -MMD -MF obj/third_party/libvpx/libvpx/fdct32x32_neon.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DOFFICIAL_BUILD -DCHROMIUM_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../../chromium-ozone-wayland-63.0.3239.132.lge.1 -Igen -I../../../chromium-ozone-wayland-63.0.3239.132.lge.1/third_party/libvpx/source/config -I../../../chromium-ozone-wayland-63.0.3239.132.lge.1/third_party/libvpx/source/config/linux/arm64 -I../../../chromium-ozone-wayland-63.0.3239.132.lge.1/third_party/libvpx/source/libvpx -Igen/third_party/libvpx -I../../../chromium-ozone-wayland-63.0.3239.132.lge.1/third_party/libvpx/source/libvpx -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-function -Wno-sign-compare -std=gnu11  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/igalia/jaragunde/genivi-salvator-x/gdp-src-build/tmp/work/aarch64-poky-linux/chromium-lge/63.0.3239.132.lge.1-r0=/usr/src/debug/chromium-lge/63.0.3239.132.lge.1-r0 -fdebug-prefix-map=/home/igalia/jaragunde/genivi-salvator-x/gdp-src-build/tmp/work/aarch64-poky-linux/chromium-lge/63.0.3239.132.lge.1-r0/recipe-sysroot-native= -fdebug-prefix-map=/home/igalia/jaragunde/genivi-salvator-x/gdp-src-build/tmp/work/aarch64-poky-linux/chromium-lge/63.0.3239.132.lge.1-r0/recipe-sysroot=  -c ../../../chromium-ozone-wayland-63.0.3239.132.lge.1/third_party/libvpx/source/libvpx/vpx_dsp/arm/fdct32x32_neon.c -o obj/third_party/libvpx/libvpx/fdct32x32_neon.o
{standard input}: Assembler messages:
{standard input}: Error: unaligned opcodes detected in executable segment
```

**Comment by jaragunde** [comment]
Hi @chbae, I didn't understand your request, sorry. Could you elaborate? There are no problems integrating with GENIVI HMI with this version (chromium-lge browser). My main issue is a compilation problem for the R-Car gen. 3, which I suspect is related with compiler versions. Chromium is known for easily breaking compilers...

**Comment by jaragunde** [comment]
I just read this on #173:
> I have a build of P-0.1 Genivi 14 Yocto Baseline on R-Car Gen 3 building locally based on upstream YBSP v3.4 and my meta-ivi-renesas. YBSP v3.4 brings various changes such as adoption of Poky meta gcc v7.x

This is likely to fix the compilation issues we have on that platform.

**Comment by gunnarx** [comment]
@jaragunde, we have a few different inputs to this now. 

There's a PR (this one) that fails overall, but it might need a rebase.  You say you have a fully working GDP HMI integration - but is that identical to this PR -- is it commit https://github.com/GENIVI/genivi-dev-platform/pull/174/commits/607e82854e607d35abcc19b0057c6366a65fcd60 ?  

Because this PR seems to fail in various ways on our CI builds at least, not only on R-Car.  If you have another working setup, can you point me to it so we can compare?  In any case I imagine this needs a rebase since GDP is also moving, including updates for rocko branch and latest GENIVI baseline, but let's start evaluating from what works.

@chbae provided a full GDP 14 update in #175 that works on all but R-Car - and with Stephen's latest fixing I'd bet it works overall.  But it looks like he had to disable chromium completely to make it build?

My own update #173 fails (on Chromium) but we need to incorporate Changhyeok's changes.  I haven't had the time to check the details but I imagine that #175 probably supersedes #173.

**Comment by jaragunde** [comment]
I'll rebase on top of @chbae 's work. I'm facing the same problem that we can see in the CI build, I'll re-post a fixed version as soon as I get it.

**Comment by slawr** [comment]
@jaragunde If you look at this [PR #2](https://github.com/chbae/genivi-dev-platform/pull/2) from me you can pick up the R-Car update.

**Comment by jaragunde** [comment]
Pushed the rebase on top of PR https://github.com/GENIVI/genivi-dev-platform/pull/175, tested on Raspberry Pi 3. I checked out the latest `meta-lgsvl-browser`, which should fix the CI problem and, as a bonus, provides Chromium 64.

@slawr I hadn't read your message, I will try an R-Car gen 3 build on top of your patches.

**Comment by slawr** [comment]
> @slawr I hadn't read your message, I will try an R-Car gen 3 build on top of your patches.
@jaragunde  thanks. Hopefully it will be quickly merged. I have successfully built #175 with it.

**Comment by gunnarx** [comment]
OK, so going through some of the build failures here...
----
R-Car build is a Linaro toolchain thing - so I'll assume it gets fixed with Stephen's PR [chbae/#2](https://github.com/chbae/genivi-dev-platform/pull/2)
---
QEMU is more tool chain stuff.  Why is chromium so goddamn picky? :-) :-)

ERROR: Logfile of failure stored in: /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-GITHUB-PR/gdp-src-build/tmp/work/core2-64-poky-linux/chromium-lge/64.0.3282.186.lge.2-r0/temp/log.do_configure.27277
12:45:41.149 Log data follows:
12:45:41.149 | DEBUG: Executing shell function do_configure
12:45:41.149 | ERROR at //build/config/sanitizers/sanitizers.gni:172:1: Assertion failed.
12:45:41.149 | assert(!is_cfi || is_clang,
12:45:41.150 | ^-----
12:45:41.150 | is_cfi requires setting is_clang = true in 'gn args'

... so OK, so chromium has some asserts in teh config about clang vs. non-clang compiler.  Not sure what to think but it should be straight forward to someone who knows how to set "gn args".  Wut? @jaragunde ?
----
Minnowboard is same as QEMU, not too surprising.  I guess it's more or less the same gcc being used?
----
Dragonboard gets "relocation overflow"... so it should need some flag to tell the linker to use larger space for the static data.   Anyone have proposal for exact change?

**Comment by gunnarx** [comment]
Looking deeper at QEMU/Minnowboard:

12:45:41.149 ERROR: Logfile of failure stored in: /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-GITHUB-PR/gdp-src-build/tmp/work/core2-64-poky-linux/chromium-lge/64.0.3282.186.lge.2-r0/temp/log.do_configure.27277
12:45:41.149 Log data follows:
12:45:41.149 | DEBUG: Executing shell function do_configure
12:45:41.149 | ERROR at //build/config/sanitizers/sanitizers.gni:172:1: Assertion failed.
12:45:41.149 | assert(!is_cfi || is_clang,
12:45:41.150 | ^-----
12:45:41.150 | is_cfi requires setting is_clang = true in 'gn args'
12:45:41.150 | See //build/config/v8_target_cpu.gni:5:1: whence it was imported.
12:45:41.150 | import("//build/config/sanitizers/sanitizers.gni")
12:45:41.150 | ^------------------------------------------------
12:45:41.150 | See //build/config/arm.gni:5:1: whence it was imported.
12:45:41.150 | import("//build/config/**v8_target_cpu**.gni")
12:45:41.150 | ^----------------------------------------
12:45:41.150 | See //build/config/compiler/compiler.gni:8:1: whence it was imported.
12:45:41.150 | import("//build/config/**arm**.gni")
12:45:41.150 | ^------------------------------
12:45:41.150 | See //BUILD.gn:11:1: whence it was imported.
12:45:41.150 | import("//build/config/compiler/compiler.gni")
12:45:41.150 | ^--------------------------------------------
12:45:41.150 | WARNING: exit code 1 from a shell command.

@jaragunde There's something strange here, right?  It looks like several ARM specific files are being used, even if the build is for x86_64.  Have you done any testing on x86?

**Comment by jaragunde** [comment]
I found a "relocation overflow" problem in the R-Car build. I'm working on it, it's probably the same issue as in the Dragonboard. My colleagues fixed a similar problem on AGL R-Car builds by forcing `-Os` instead of `-O2`.

**Comment by jaragunde** [comment]
Pushed a new version, rebased on top of @slawr 's work for R-Car, and including a patch to fix the ARM64 relocation overflow errors. Let's see what's the CI output.

**Comment by jaragunde** [comment]
BTW, I'm finding that the images I build don't run the GDP HMI by default, I have to start it with `systemctl --user start gdp-new-hmi`. Is that expected?

**Comment by jaragunde** [comment]
@slawr This happened in all the builds I've tried so far: Raspberry Pi 3, R-Car M3 and Minnowboard. I can start the HMI manually by starting the HMI service and then restarting Weston. The application launchers seem to freeze the HMI, but applications can be ran manually.

**Comment by gunnarx** [comment]
Confirming my own comment:

> @jaragunde For R-Car, the CI build might need the script fix 

Yes, as expected we see the same build failure that fails to fetch the right graphics driver.  
#177 which puts everything together should let us know if it's OK however.

The result for RPI2 is showing failure because I stopped the build (sorry).  
We can confirm based on #177 result, or I'll try to re-run that one later.

**Comment by slawr** [comment]
@jaragunde ok interesting its on multiple boards. We discussed some possible causes in the BIT call this morning. Most likely is multiple layers using layer ID 0. The bring up discussion is starting to get fragmented over a few PRs so Oscar has raised JIRA https://at.projects.genivi.org/jira/browse/GDP-778 to focus the discussion in one place.

Locally I can not even manually start the HMI using what you outlined but I'll provide details in the ticket.

**Comment by gunnarx** [comment]
As noted, this has been folded into later PRs, e.g. #177 so we can close it.  

I can confirm that after HMI and app launching is fixed again it seems to work to the level it has before, on #177 .  I have tested on QEMU, and chrome://version reports 64.0.3282.186.

**Pull request closed without merging**
