### PR TITLE
renesas-rcar-gen3: Rebase on Yocto BSP v2.19

### PR DESCRIPTION
**Pull request by slawr**
The Genivi 12 branch of the Renesas R-Car Gen 3 Genivi Yocto BSP has
been updated to use v2.19 of the upstream Yocto BSP. Update to this
newer version.

This has been sanity tested on the following boards:
M3 Starter Kit
M3 Salvator-X
H3 Salvator-X

Signed-off-by: Stephen Lawrence <stephen.lawrence@renesas.com>

I tried to use the git-submodule-bump script to create the commit but
could not get it to work as expected. If someone can show how it works
I can push a new commit if you wish.

### CODE REVIEW

**Comment by gunnarx** [comment]
> I tried to use the git-submodule-bump script to create the commit but
could not get it to work as expected. If someone can show how it works
I can push a new commit if you wish.

- It doesn't work if you already did "git add" on the submodule.
- (If more than one submodule has changed it will just pick the first one.)

I would like to change it because I **always** amend the commit anyway:

Current behavior:
 - You must specify the commit summary line from the command line and remember to not mention the submodule name because it is prepended automatically.
 - Script will git add and commit the first changed submodule it finds

Alternative behavior (that I want):
- specify the changed submodule on command line
- script will git add the _specified_ submodule, if it's not already in the index
- opens an editor to allow you to finish the commit message, including typing out the summary in the editor, instead of on the command line.

**Comment by slawr** [comment]
Thanks for the hint Gunnar.

Tried again with mixed results:
```
steve@be1yocto:~/genivi/genivi-12/m3sk/genivi-dev-platform$git checkout -b test origin/master    
M       renesas-rcar-gen3
Branch test set up to track remote branch master from origin.
Switched to a new branch 'test'
steve@be1yocto:~/genivi/genivi-12/m3sk/genivi-dev-platform$ git status
On branch test
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   renesas-rcar-gen3 (new commits, untracked content)

[snip]
steve@be1yocto:~/genivi/genivi-12/m3sk/genivi-dev-platform$ ./git-submodule-bump "Rebase on Yocto BSP v2.19" 
./git-submodule-bump: 29: ./git-submodule-bump: MSG+=$\n\n: not found
./git-submodule-bump: 30: ./git-submodule-bump: MSG+=aa6a28b: not found
[test 01cc26b] renesas-rcar-gen3: Rebase on Yocto BSP v2.19
 1 file changed, 1 insertion(+), 1 deletion(-)
steve@be1yocto:~/genivi/genivi-12/m3sk/genivi-dev-platform$ git log
commit 01cc26b379d09eee9d50c4ad814a97ad890ae45e
Author: Stephen Lawrence <stephen.lawrence@renesas.com>
Date:   Thu Jun 8 20:11:48 2017 +0100

    renesas-rcar-gen3: Rebase on Yocto BSP v2.19
    
    Signed-off-by: Stephen Lawrence <stephen.lawrence@renesas.com>

commit b21192b22d9447d2e80bfdb1f262f0b763dee554
Author: Gunnar Andersson <gandersson@genivi.org>
Date:   Sat May 27 20:07:35 2017 +0200

    ci-build.sh: Update submodules before printing them
```

I guess from the script line number warnings there were problems extracting the summaries.

**Comment by slawr** [comment]
I think your suggested improvements to the helper script would be good Gunnar.
So as not to clutter up this PR I have created JIRA [GDP-638](https://at.projects.genivi.org/jira/browse/GDP-638) for the seperate issue I found with the helper script.

**Comment by gunnarx** [comment]
> ./git-submodule-bump: 29: ./git-submodule-bump: MSG+=$\n\n: not found
> ./git-submodule-bump: 30: ./git-submodule-bump: MSG+=aa6a28b: not found

I think appending like that is a [bashism](http://mywiki.wooledge.org/Bashism) and maybe another shell was invoked?  We should fix the #! line, or remove the bashisms.

In the meantime if you have bash on the machine, you could likely try:
```
bash git-submodule-bump "summary"
```

**Comment by slawr** [comment]
Updated PR commit msg with manual insert of commit log the script produces, otherwise no other change.

**Comment by gunnarx** [comment]
Commit looks good. I'll rebase and merge on top of the m-g-d subtree merge (unrelated change, so no worries).

**Comment by slawr** [comment]
> Hmm, it seems the R-Car build was successful - no need to update binary drivers?
>
Sorry missed the question.

We discussed in the GDP call, but adding a note here for the record as I see I didn't actually address it in the PR message.

In summary, the updates for Yocto BSP v2.19 included updated gfx and mmp packages. Please download the "click through" license packages for v2.19. Earlier versions may work, but I do not know if they are compatible and will not have the latest fixes.

See my [blog post](https://at.projects.genivi.org/wiki/display/PROJ/2017/06/08/Renesas+R-Car+Gen+3+Genivi+12+support+updates+to+Yocto+BSP+v2.19) on the Genivi wiki for details.

**Comment by gunnarx** [comment]
Drivers downloaded and a few agents are set up for these builds ([GDP-661](https://at.projects.genivi.org/jira/browse/GDP-661))
The ticket pertaining to the actual content of this PR is [GDP-679](https://at.projects.genivi.org/jira/browse/GDP-679)

**Pull request merged**
