### PR TITLE
Feature sdl pyro

### PR DESCRIPTION
**Pull request by frznlogic**

### CODE REVIEW

**Comment by gunnarx** [comment]
Reviewed only the 4 new commits.  The changes look good to me.   A new failure in Qt compilation to fix though.

**Comment by frznlogic** [comment]
I hope to have fixed the pyqt issues now, I also speeded up the build somewhat.

**Comment by gunnarx** [comment]
R-Pi build:
01:43:07.424 | collect2: fatal error: ld terminated with signal 9 [Killed]

I'm guessing this ran out of memory or got stuck somehow and therefore killed?  Trying a restart.

**Comment by frznlogic** [comment]
I'm currently trying to reproduce, there was a followup error afterwards:
```
01:43:07.424 | /var/lib/go-agent/pipelines/GDP-Yocto-RPI2-GITHUB-PR/gdp-src-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/chromium-wayland/53.0.2785.143-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/../../libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/6.3.0/ld: error: chrome(.debug_info) is too large (0xb3e0ad4c bytes)
01:43:07.424 | /var/lib/go-agent/pipelines/GDP-Yocto-RPI2-GITHUB-PR/gdp-src-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/chromium-wayland/53.0.2785.143-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/../../libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/6.3.0/ld: error: chrome(.debug_str) is too large (0x1f96bba3 bytes)
```

**Comment by gunnarx** [comment]
I made sure that the rebuild runs on a different agent for comparison.

**Comment by frznlogic** [comment]
The build ran fine locally for rpi2, but it used up to 16GB of RAM to link chrome....

**Comment by frznlogic** [comment]
RPi2 is fine now....

**Pull request merged**
