### PR TITLE
Switched meta-ivi submodule url to Github upstream

### PR DESCRIPTION
**Pull request by tom--pollard**

### CODE REVIEW

**Comment by chbae** [comment]
Why do you change meta-genivi-dev in this commit?
This PR is only for meta-ivi change?

**Comment by tom--pollard** [comment]
@chbae I've sent a separate PR for meta-genivi-dev, because it includes more changes than just the github upstream changes within it

**Comment by tom--pollard** [comment]
@chbae oh sorry I see what you mean, not 100% what has gone wrong here. Will fix it tomorrow thanks for the catch!

**Comment by tom--pollard** [comment]
I've amended the commit to remove the sha change of meta-genivi-dev

**Comment by gunnarx** [comment]
It looks like these commits have been merged.
So the PR can be closed?  With @tom--pollard out of office, up to you to decide @RobertAJMarshall?

**Comment by chbae** [comment]
@tolkien-joh 

Will you manage meta-ivi in yoctoproject git repo or github/genivi?
I thought that you may select github/genivi :). Then are you mirroring meta-ivi to yoctoproject git repo?

According to @tolkien-joh 's answer, I'll decide to merge this PR.

**Comment by tolkien-joh** [comment]
Hi ChangHyeok.

github.com is what I workis today.
yoctoproject.git will be backup for times.

**Comment by chbae** [comment]
@tolkien-joh 
Thanks. I'll merge this chagne.

**Pull request merged**
