### PR TITLE
meta-iot-web: Update to latest master

### PR DESCRIPTION
**Pull request by gunnarx**
Should fix [GDP-571] Iotivity build failure on Dragonboard

(Like https://github.com/GENIVI/genivi-dev-platform/pull/68 but better...)

Note this brings in some additional updates made on meta-iot-master.  They appear harmless to me but @rzr might help us confirm that they should not cause any trouble with our features.

More details in commit message.

Let's wait for CI builds to succeed first.

### CODE REVIEW

**Comment by rzr** [comment]
yea good to me thanks @gunnarx it was quick !

https://github.com/ostroproject/meta-iot-web/pull/35#event-1008410153

Meanwhile I have commited iotivity-1.2.1 in meta-oic, so I will double check all on next upgrade (no ETA yet, but It's on my plan).

**Comment by zeenix** [comment]
@gunnarx Just merged the PR from @chbae that removes merge commits from the log. Could you please re-do the commit with the script again?

**Comment by gunnarx** [comment]
There's no merge commit in my PR, is there?

**Comment by zeenix** [comment]
@gunnarx Not in the PR but your commit log (summary of changes in submodule).

**Comment by gunnarx** [comment]
I think you are referring to meta-iot-web?  With this PR I am back on the upstream meta-iot-web again.  It's up to them if they want merge commits or not - I have no control over it.   

OK, so you want the commit log to be edited and not be exactly the same as the submodule log?

**Comment by zeenix** [comment]
@gunnarx yes but we can remove them. Update to latest git master in g-d-p and redo the git commit and you're golden.

**Comment by rzr** [comment]
Thank you again, for that contribution to meta-oic-web,
but I am wondering why wasnt it trapped earlier ? I will ask in call.

**Comment by rzr** [comment]
answer is that it aarch64 was not enabled in the build farm, so I will double check on iotivity-1.2.1 and iotivity-1.3.0 next.

To be tracked at:
http://wiki.iotivity.org/automotive

**Pull request merged**
