### PR TITLE
poky: Update to latest krogoth (b4df9df4)

### PR DESCRIPTION
**Pull request by zeenix**
This is to fix https://at.projects.genivi.org/jira/browse/GDP-577 .  The issue unfortunately also affects gdp-11 so we need to apply this on that branch too.

**NOTE**: The fix in question is no longer needed but as said in comments, better update anyway.

### CODE REVIEW

**Comment by chbae** [comment]
Looks good for me but I'll wait for CI result and then merge it.

**Comment by zeenix** [comment]
@chbae Yeah, I wouldn't want to merge before that either. :)

**Comment by chbae** [comment]
@zeenix 
Last file commit in upstream is reverted because upstream restored the original hashes.
So we don't need to take this PR.

**Comment by zeenix** [comment]
@chbae Oh good. That's good to hear.

**Comment by zeenix** [comment]
@chbae However, I think we should update to latest stable branch anyway, since there are many fixes. Hopefully we'll soon move to morty, thanks to your awesome work but in case we don't in release 12, we should be on latest krogoth at least.

**Comment by chbae** [comment]
@zeenix Then you need to add 1 more commit (Revert file: update SRCREV for 5.25 to fix fetch fail on missing commit) from krogoth branch of upstream.

**Comment by zeenix** [comment]
@chbae actually I already did but seems I forgot to put that change in commit log. I'll fix that now..

**Comment by chbae** [comment]
Dragonboard failure cause that this commit is not latest but it's fine. I'll merge it.

**Pull request merged**
