### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeremiah**
Changed the headline, tried to clarify branch usage.

### CODE REVIEW

**Comment by jeremiah** [comment]
Not needed, closing.

**Comment by gunnarx** [comment]
I don't understand "not needed".  The changes are good and I've been wanting to make a similar one for quite some time.  So if you no longer  want to submit this change then I will :-)
(By the way, the commit can be recovered from the repo even if the branch was deleted - I just checked)

**Comment by jeremiah** [comment]
Okay, sorry for the confusion. My aim was to simplify the README. While I may be confused still by which branch to apply this too I'm happy for someone to merge.

**Comment by tom--pollard** [comment]
I'm ok to add this patch to all target branches, however it won't include the github PR merge commit

**Comment by jeremiah** [comment]
That's fine with me. :-)

**Comment by tom--pollard** [comment]
Merged onto all targets, thanks

**Comment by gunnarx** [comment]
Thanks for merging.  I deleted the branch that remained.  GitHub had a button for it so... :-)

**Pull request closed without merging**
