### PR TITLE
[WIP] Upgrade Qt to v5.6.3

### PR DESCRIPTION
**Pull request by chbae**
Qt company manages vendor branch.
So GDP changes meta-qt5 layer to git://code.qt.io/yocto/meta-qt5.git

qtdeclarative: Two patches are applied to v5.6.3.
- 0001-V4-Free-up-2-address-bits-in-64bit-mode.patch
- 0002-V4-Fix-usage-of-QV4-Value-tags-types.patch

Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

### CODE REVIEW

**Comment by gunnarx** [comment]
Thanks @chbae!

So nice to get rid of those patches!  I assume those patches are already applied in 5.6.3?  
(It takes some work to follow from GDP submodule update - to the diff in bb files - and then to checking the actual source code changes...)

Oh, if I had a direct communication line to the Qt devs I'd tell them that:
fa73caf  Mikko Gronoff  5 weeks ago (authored 6 weeks ago)  **qt5: update submodules**
c3e7bf0  Mikko Gronoff  9 weeks ago (authored 9 weeks ago)  **qt5: update submodules**
b72dbdf  Mikko Gronoff  10 weeks ago (authored 4 months ago) **qt5: update submodules**

is kind of lazy...  Yes inside the full commit comment it is stated that the update is for 5.6.3 (snapshot 1, 2 RC1, and so on), but please put that in the summary so that it can be easily seen and searched for when doing a short log!  :-(

As you said, we should test carefully before merging.

**Comment by gunnarx** [comment]
Rebase on master (includes HVAC fix + some build script updates, both of which might be good for testing)

**Comment by chbae** [comment]
No I just rebased and need to test. I'm on business trip.
I'll test in end of next week in qemux86 and raspberrypi3.

**Comment by frznlogic** [comment]
Hi chbae, 

I'll get on testing this tomorrow, but really good work, thank you!

**Comment by chbae** [comment]
@frznlogic Did you test this? I didn't test it. :(

**Comment by frznlogic** [comment]
@chbae I was a bit delayed in the testing i'm afraid, but finally got around to it. I've gotten all the platforms I have available to boot into the HMI and all apps start and behave decently from what I can tell. I'll rebase and merge the PR.

**Pull request merged**
