### PR TITLE
cannelloni: Fix license check warning

### PR DESCRIPTION
**Pull request by chbae**
WARNING: cannelloni-1.0-r0 do_populate_lic: Could not copy license file
...........
[Errno 2] No such file or directory:
'.../gdp/poky/meta/files/common-licenses/GPLv2'

Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

### CODE REVIEW

**Comment by chbae** [comment]
@frznlogic, @gunnarx 
Please review this change.

**Comment by gunnarx** [comment]
Thanks for cleaning this up @chbae.  Approved of course, and we must apologized for slow reactions on these - not really acceptable.   

I did remember looking at this earlier when it arrived but apparently I did not comment. @frznlogic - another one to merge when master is stable.  

We've apparently missed merging some of these easy ones (and I've been a lot more busy with other non-coding stuff the last two weeks, fyi)

**Comment by gunnarx** [comment]
Discussed on this morning's stand-up.  Now that master is fixed, we just need to rebase and rebuild.

**Comment by frznlogic** [comment]
Rebased and uploaded to your branch. I'll have a look at it once the build has gone through and probably merge it.

**Comment by gunnarx** [comment]
Build check looks OK.   QEMU error is an agent issue we are looking at.  I retriggered it on another agent but I can't see we need to wait for that.

**Pull request merged**
