### PR TITLE
Update meta-ivi & configure hardening flags

### PR DESCRIPTION
**Pull request by gunnarx**
Nitpick: the commit comment says it is updating to master.  In reality I pushed branch wip_hardening_flags to GENIVI/meta-ivi so the commit can be referenced from GDP while it's still only an open PR in meta-ivi.
If we merge that without additional changes, the commit history and "latest master" will be correct.  Otherwise I can rewrite this commit to match.

(see commit comment for log)

### CODE REVIEW

**Comment by gunnarx** [comment]
meta-ivi PR reference https://github.com/GENIVI/meta-ivi/pull/60

**Comment by gunnarx** [comment]
Pushed an update with a longer commit comment for "Blacklist some packages from compiler hardening flags"

**Comment by frznlogic** [comment]
Do you mind if we wait until the chrome pr is pulled in first?

**Comment by gunnarx** [comment]
I don't mind.  PR merge order is always whatever team thinks is appropriate.
Rebased for new build check.

**Comment by gunnarx** [comment]
We'll just take this as part of the rocko update since meta-gplv2 is updated there.

**Comment by phongt** [comment]
please note that the gettext fixing is only merged in [master](https://git.yoctoproject.org/cgit/cgit.cgi/meta-gplv2/log/)

**Comment by gunnarx** [comment]
Rebased this on latest origin/master, and new build checks.  I expect it might still fail however since the PR is built on master (GDP 13) but requires related changes in baseline that are only on 14 branch now (if I recall correctly).  Anyway, I'm not aware of anything more that really needs to be done on this - it should be OK once merged toward baseline/GDP 14 status.  Will confirm.

**Comment by gunnarx** [comment]
A lot of churn right now that we need to get through but overall this PR looks quite alright.

So, to comment on the build failures after the last rebase.  For R-Car it's an issue that the CI is not supporting both versions of SGX binary drivers at the same time.  CI agents have been updated to the one compatible with GDP 14, and therefore the master (GDP 13) that the PR is applied to fails in CI builds.  Supporting more than one is solvable of course, but it's not done that way now.  Anyway not a fault of this PR.

For Dragonboard there's a link failure in chromium build.  This *could* presumably be affected by the hardening flags, or not.  I think we'll know only after merging #177 and applying this on top.

I'd say this PR needs to go on top of #177 only after that has been merged.

**Comment by gunnarx** [comment]
By the way, this PR updates meta-ivi in d63f92a, but also #177 and friends update to even later versions.  So presumably that commit should be omitted when this is based on top of GDP 14.

**Comment by gunnarx** [comment]
This is way obsolete.  For example meta-ivi update in 28028f8  (on master branch) brings meta-ivi to tag P-0.1.  It supersedes this PR, except for the hardening flags that were apparently merged a bit later.  Next update to P-1.0 should bring in all of it.  Let's redo it.

**Pull request closed without merging**
