### PR TITLE
meta-oic: Update to 1.2.0

### PR DESCRIPTION
**Pull request by rzr**
Bug: https://at.projects.genivi.org/jira/browse/GDP-160
Change-Id: If862acf95b041fe7c60d7aa185245fd52e8cb489
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by rzr** [comment]
ChangeIds are used to track patches between branches or projects, 
because commit id are changing on each move ChangeIds don't, gerrit use them

URL can save you time if you want to open
https://at.projects.genivi.org/jira/browse/GDP-160

I dropped boths are requested

**Comment by zeenix** [comment]
> Note that aarch64 platform will need an other patch which is not yet merged upstream at:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-oic

Does that mean this PR breaks aach64?

**Comment by rzr** [comment]
I forwarded patches to upstream,
https://lists.yoctoproject.org/pipermail/yocto/2017-January/033696.html

Meanwhile it be can patched downstream with a bbappend file,
but where to put recipe ?

Then both PR should be merged at once.

**Comment by slawr** [comment]
Hi Philippe, you could do it by adding recipes-core/iotivity/iotivity_1.2.0.bbappend to meta-genivi-dev, but whether it is worth doing depends on timing. If it will be accepted upstream quickly and this update would be accepted normally into GDP and it is not time critical I would suggest waiting for upstream to update.

**Comment by zeenix** [comment]
@rzr So what's the plan here? We wait for this to work on aarch64? If so, I'd want to close this PR for now.

**Comment by rzr** [comment]
well I am waiting for upstream reviewer @kmaloor 

Once merged in:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-oic

I will refresh this change, as suggested above, so better keep it open, for others working on similar subject:
https://openiotelcna2017.sched.com/event/9J5L/genivi-and-iotivity-support-where-we-are-and-where-we-need-to-go-nivedita-singhvi-urbansystems

I am working on private repo for now.

**Comment by slawr** [comment]
Hi, just to be clear I don't see a problem carrying the 64-bit patch if there is an urgency. I'm not a GDP maintainer and I don't mean to say this PR should be blocked by waiting for the upstream. I don't have a complete view of what the team is trying to achieve here. I just meant if the 64-bit patch appeared upstream soon then that will avoid you adding the bbappends and directories to apply the fix.

**Comment by rzr** [comment]
I am following suggested workflow:  rebase on upstream and will reach @kmaloor maintainer, if no news before end of month.

**Comment by zeenix** [comment]
@rzr thanks! I really would like to see PRs as TODO for GDP maintainers, hence the reason I asked for this to be closed. Also like @slawr I'd like to avoid having patches whenever possible. I hope you understand. Feel free to keep and advertise a branch until this is ready for prime time.

**Comment by rzr** [comment]
upstream merged my patch, so I will update meta-oic

**Comment by rzr** [comment]
I am considering to add iotivity-node next,
as we used it for gateway etc

Is there anything more needed, got merging this PR?
I will not break dragon board

I will update:
https://wiki.iotivity.org/automotive#

cc: @gunnarx @iamsanjeev

**Comment by gunnarx** [comment]
> Is there anything more needed, got merging this PR?

@rzr, sorry I don't understand "got merging"

>  I will not break dragon board

Does this mean that you confirm that the PR, as it stands now, does not break the aarch64 build, or does it mean something else?

Thanks for clarifying...

**Comment by rzr** [comment]
sorry "to get this PR merged, yea all needed fixes are merged upstream, I am just pulling them back with this update.

**Comment by rzr** [comment]
this is not latest release so it can be confusing, but I can change it if it helps, beside that is it ok to merge ?

**Comment by zeenix** [comment]
@rzr If it's not latest, neve mind. The only other issue I see is that you have two commits, each updating the same submodule. Surely, we need only one?

**Comment by rzr** [comment]
Is it a problem since they are in the same PR, It wont change anything your side

I can squash them if needed

**Comment by zeenix** [comment]
I don't see the point of them being separate so yes, please squash them.

**Comment by zeenix** [comment]
Thanks, almost there. I see a redundant newline in the commit message. Just remove that and we're good to merge already. :)

**Comment by rzr** [comment]
Please tell me where are these redundant newlines ?

https://github.com/TizenTeam/genivi-dev-platform/commit/d337a00abed29dd21e1c358bd2657f7dff70b0c0.patch

I believe I am aligned to:
https://at.projects.genivi.org/wiki/display/PROJ/Rules+for+Commit+Messages

**Comment by ns950** [comment]
Hello zeenix, 

Is it OK for the title to be taken from the SUBJECT line of the email post? I'm assuming that's fine, right...(I am new to this project, and trying to understand the patch submission rules).

Nivedita

**Comment by zeenix** [comment]
@rzr I believe my comment came *before* your last update. There is no redundant newline but as I explained on IRC, you're breaking off line too early and adding a space in front of second line. It's a very small thing so I mentioned on IRC to save time. If you had just fixed it, it would have taken you a minute at most and your branch would have been merged already. Instead we ended up with a long discussion that only lead you in the end to get angry.

The rules (whose URL was unknown to you until I informed on IRC *after* your last update) don't, can't and shouldn't cover everything. The details part of commit message is plain English and you're expected to follow the general conventions and grammar, besides the rules.

**Comment by zeenix** [comment]
@ns950 The subject/shortlog/title of commit messages, are expected to be the same as email subject, yes. Which is why there is a limit of 50 chars.

**Comment by rzr** [comment]
Sorry I just a bit confused  please confirm if current version of patch is matching your requirement or not ?
Because current state is "Changes requested" so I don't know what should be done my side.

You can reach me on IRC or here, It's up to your preference.

@ns950 I know you need this change in GDP, but if it is not merged on time, I will give all needed instructions at: 
https://wiki.iotivity.org/automotive

Please @ns950 tell if you're able to reproduce that, then I can give you more details on how to run the FOSDEM demo on GDP:

http://www.slideshare.net/SamsungOSG/iotivity-from-devices-to-the-cloud-71867171

Hope this help

**Comment by rzr** [comment]
@jeremiah , I think there is something missleading in github flow.
I just updated the commit message again (with help of @zeenix) and the state is "Changes requested" while you haven't reviewed it, did you ? I expect it to be something like "Updated change not yet reviewed" ? Or am I missing something ? this can lead to misunderstanding between commiter and reviewer ?

**Comment by zeenix** [comment]
@rzr the status remains the same until the reviewer verifies that your new patches have addressed the issues pointed out in the last review.

**Comment by rzr** [comment]
Ok thanks @zeenix for the merge, but regarding the flow if reviewer think new same issues should be addressed, does it appear differently ? maybe at different place in the message stack.

Well let me close the PR now, and thank you for time and patience.

**Comment by zeenix** [comment]
> Ok thanks @zeenix for the merge, but regarding the flow if reviewer think new same issues should be addressed, does it appear differently ? maybe at different place in the message stack.

AFAICT, all updates/messages appear in chronological order so it's possible to follow what happened, when. I agree that the notification of updates should be more pronounced.

> Well let me close the PR now, and thank you for time and patience.

No worries, same to you. :)

**Pull request merged**
