### PR TITLE
raspberrypi2.local.conf: Use same configuration with rpi3

### PR DESCRIPTION
**Pull request by chbae**
Only configuration difference of raspberrypi2 and raspberrypi3 is
MACHINE variable.

[GDP-248] Question about differences in local conf rpi2 / rpi3

Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

### CODE REVIEW

**Comment by gunnarx** [comment]
Thanks Changhyeok hanks for making this more similar.  It seems OK but I am guessing some run-time testing of the image is also a good idea for this type of change.  Even if it compiles maybe there is some risk of changed behavior?

Comment for any casual readers:  There seems to be some error in compiling Rust on all hardware except QEMU and this i why the PR test build failed on all except QEMU.  The build failure is not related to this PR.   I guess the GDP team will look into it.

**Comment by tom--pollard** [comment]
@gunnarx Yep seeing the rust failures on go.cd, it's not always the same error/recipe either.

**Comment by tom--pollard** [comment]
Is there a reason why the bcm2709-rpi-2-b.dtb overlay is not necessary any more?

**Comment by chbae** [comment]
@tom--pollard 
the bcm2709-rpi-2-b.dtb is included in default device tree file. you can see the device tree files in conf/machine/include/rpi-base.inc

**Comment by tom--pollard** [comment]
@chbae thanks for pointing me to it, +1.

**Comment by gunnarx** [comment]
Chbae - could you or someone build it and also make a quick smoke test on RPi 2 and 3 before merging?

**Comment by chbae** [comment]
@gunnarx 
I already tested on rpi2 before pull request and it works. This commit only affects in rpi2.

**Comment by tom--pollard** [comment]
Please feel free to merge this @chbae

**Pull request merged**
